---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-entitlements-.html 
summary: Recuperar um direito 
---
= Recuperar um direito
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/entitlements/{entitlement_id}`#

Retorna o recurso da API Entitlement armazenado no corpo da resposta JSON.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| entitlement_id | string | caminho | Verdadeiro  a| 
ID da coleção de direitos a ser listada

|===


== Resposta

[source]
----
Status: 200, Returns the stored Entitlement API resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-entitlement"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| alocação | string | Falso  a| 
String JSON contendo o ID do objeto ao qual o direito está alocado. Presente apenas quando o direito está alocado. O conteúdo da string não foi validado pelo esquema.



| produto | string | Falso  a| 
Cadeia JSON contendo a string do produto extraída da licença ou assinatura. O conteúdo da string não foi validado pelo esquema.



| productVersion | string | Falso  a| 
String JSON contendo a string de versão extraída da licença ou assinatura. O conteúdo da string não foi validado pelo esquema.



| entitlementType | string | Verdadeiro  a| 
String JSON contendo o tipo de direito. Este valor é extraído da licença ou assinatura. O conteúdo da string não foi validado pelo esquema.



| entitlementValue | string | Verdadeiro  a| 
String JSON contendo a capacidade associada ao entitlement. O conteúdo da string não foi validado pelo esquema.



| entitlementConsumption | string | Falso  a| 
String JSON contendo a quantidade de capacidade associada à licença que está atualmente em uso. O conteúdo da string não foi validado pelo esquema.



| sourceLicense | string | Falso  a| 
String JSON contendo o ID do objeto de licença do qual a entitlement é originada. Os valores definidos são:

* Conforme o esquema de identificador Astra




| sourceSubscription | string | Falso  a| 
String JSON contendo o ID do objeto de assinatura do qual o direito é originado. Os valores definidos são:

* Conforme o esquema de identificador Astra




| validFromTimestamp | string | Falso  a| 
String JSON contendo um carimbo de data/hora indicando quando o direito se torna válido. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| validUntilTimestamp | string | Falso  a| 
String JSON contendo um carimbo de data/hora indicando quando o direito deixa de ser válido. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| metadados | link:#type_astra_metadata["tipo_metadados_astra"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Conforme o esquema de metadados Astra


|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-entitlement",
  "version": "1.0",
  "id": "8bdafc19-bde6-5f45-9808-4893c845c9f5",
  "product": "Astra SDS",
  "productVersion": "1.0",
  "entitlementType": "capacity",
  "entitlementValue": "2",
  "entitlementConsumption": "1",
  "sourceLicense": "c8aa757a-5318-489f-8134-a2a1a6956a3e",
  "validFromTimestamp": "2020-08-06T00:00:00.000000Z",
  "validUntilTimestamp": "2021-08-06T00:00:00.000000Z",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_metadados_astra

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Conforme o esquema de metadados Astra


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Verdadeiro  a| 



| CriaçãoTimestamp | string | Verdadeiro  a| 



| Alteração do Timestamp | string | Verdadeiro  a| 



| CreatedBy | string | Verdadeiro  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====