---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-clouds-clusters-namespaces-.html 
summary: Recuperar um namespace para uma nuvem 
---
= Recuperar um namespace para uma nuvem
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clouds/{cloud_id}/clusters/{cluster_id}/namespaces/{namespace_id}`#

Retorna o recurso da API Namespace armazenado no corpo da resposta JSON.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| id_da_nuvem | string | caminho | Verdadeiro  a| 
ID do recurso de nuvem que o contém



| cluster_id | string | caminho | Verdadeiro  a| 
ID do recurso de cluster que o contém



| namespace_id | string | caminho | Verdadeiro  a| 
ID da coleção de namespace a ser listada

|===


== Resposta

[source]
----
Status: 200, Returns the stored Namespace API resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-namespace"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| links | array[link:#type_astra_link["tipo_astra_link"]] | Verdadeiro  a| 
Links que descrevem as operações suportadas no recurso.



| nome | string | Verdadeiro  a| 
String JSON contendo um valor que indica o nome do namespace. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 255




| namespaceState | string | Verdadeiro  a| 
String JSON contendo um valor que indica o estado do namespace. Os valores definidos são:

* "descoberto" - O namespace foi encontrado no cluster
* "removido" - O namespace foi excluído do cluster ou o cluster não está sendo gerenciado, mas pode haver recursos que se referem ao namespace




| namespaceStateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Verdadeiro  a| 
Matriz JSON de objetos JSON que lista detalhes adicionais sobre o motivo da transição do "estado" para o "estado a", "estado b" ou "estado c". Se não houver detalhes disponíveis, essa matriz estará vazia. Os valores definidos são:

* Itens mínimos: 0




| kubernetesLabels | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 
Matriz JSON de objetos JSON, cada um contendo um rótulo do Kubernetes associado ao namespace. Os valores definidos são:

* Está em conformidade com o esquema de matriz de rótulos do Kubernetes




| ID do cluster | string | Verdadeiro  a| 
String JSON contendo um identificador globalmente único do cluster no qual o namespace está contido. Os valores definidos são:

* Conforme o esquema de identificador Astra




| systemType | string | Falso  a| 
String JSON que indica que o namespace é um tipo de namespace do sistema. Este campo identifica que tipo de namespace do sistema, se houver, o namespace é (somente versão 1.1). Os valores definidos são:

* "kubernetes" - Um namespace genérico de sistema Kubernetes (K8s), por exemplo, "kube-system"
* "netapp" - Um namespace de sistema NetApp, por exemplo, "trident" ou "netapp-monitoring"
* "openshift" - Um namespace de sistema OpenShift, por exemplo, "openshift-monitoring"
* "rke" - Um espaço de nomes do Rancher, por exemplo, "cattle-logging"
* "outros" - Namespaces de sistema comuns que não se encaixam necessariamente em outros lugares, por exemplo, "ingress-nginx", "tekton-system"




| metadados | link:#type_astra_metadata["tipo_metadados_astra"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Conforme o esquema de metadados Astra


|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-namespace",
  "version": "1.1",
  "id": "2de811a6-ce8f-512c-9c3a-9585ca66de22",
  "links": [
    {
      "rel": "canonical",
      "href": "/accounts/0b311ae7-d89a-4a11-a52c-1349ca090415/topology/v1/namespaces/7d451d2f-196e-4234-aee9-7e2376047e63",
      "type": "application/vnd.netapp.astra.namespace"
    },
    {
      "rel": "collection",
      "href": "/accounts/0b311ae7-d89a-4a11-a52c-1349ca090415/topology/v1/clouds/e0490197-872e-4de8-9287-b04a938e801f/clusters/0f284377-e5dc-4dcd-bacd-3197f2b8a347/namespaces",
      "type": "application/vnd.netapp.astra.namespaces"
    }
  ],
  "name": "kube-system",
  "namespaceState": "discovered",
  "namespaceStateDetails": [
    {
      "type": "https://astra.netapp.io/stateDetails/9",
      "title": "Namespace Discovered",
      "detail": "The namespace was discovered in the indicated managed cluster"
    }
  ],
  "kubernetesLabels": [
    {
      "name": "app.kubernetes.io/environment",
      "value": "dev"
    }
  ],
  "clusterID": "0f284377-e5dc-4dcd-bacd-3197f2b8a347",
  "systemType": "kubernetes",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
targetSchema

[role="api-collapsible-fifth-title"]
aceitar-post

[role="api-collapsible-fifth-title"]
aceitar-put

[role="api-collapsible-fifth-title"]
dicas

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| status | string | Falso  a| 



| permitir | array[string] | Falso  a| 



| aceitar-post | link:#accept-post["aceitar-post"] | Falso  a| 



| permissões | array[string] | Falso  a| 



| aceitar-put | link:#accept-put["aceitar-put"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_link

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| rel | string | Verdadeiro  a| 



| href | string | Verdadeiro  a| 



| tipo | string | Falso  a| 



| targetSchema | link:#targetSchema["targetSchema"] | Falso  a| 



| título | string | Falso  a| 



| dicas | link:#hints["dicas"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_metadados_astra

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Conforme o esquema de metadados Astra


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Verdadeiro  a| 



| CriaçãoTimestamp | string | Verdadeiro  a| 



| Alteração do Timestamp | string | Verdadeiro  a| 



| CreatedBy | string | Verdadeiro  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====