---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-executionhooks-.html 
summary: Recuperar um gancho de execução para um aplicativo 
---
= Recuperar um gancho de execução para um aplicativo
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHooks/{executionHook_id}`#

Retorna o recurso da Execution Hook API armazenado no corpo da resposta JSON. Também preenche matchingContainers e matchingImages com base no matchingCriteria atual e no app definido.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| app_id | string | caminho | Verdadeiro  a| 
ID do recurso do aplicativo que o contém



| executionHook_id | string | caminho | Verdadeiro  a| 
ID da coleção executionHook a ser listada

|===


== Resposta

[source]
----
Status: 200, Returns the stored Execution Hook API resource in the JSON response body. Also populates matchingContainers and matchingImages based on the current matchingCriteria and the defined app.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "aplicação/astra-executionHook"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| nome | string | Verdadeiro  a| 
String JSON contendo um nome especificado pelo usuário para o recurso. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63. O nome deve ser único em todos os recursos do execution hook.




| hookType | string | Verdadeiro  a| 
String JSON que define o tipo de gancho. Os valores definidos são:

* "netapp" - NetApp gancho de execução fornecido.
* "custom" - Vinculado a um ID de aplicativo específico. Os recursos de gancho de execução com hookType "netapp" são somente leitura.




| matchingCriteria | array[link:#matchingCriteria["matchingCriteria"]] | Verdadeiro  a| 
Matriz JSON de objetos JSON que descrevem os critérios de correspondência para o gancho de execução. Quando vários matchingCriteria são especificados, um operador lógico AND é aplicado aos critérios. Os valores definidos são:

* Itens mínimos: 0
* Máximo de itens: 10




| matchingContainers | array[link:#matchingContainers["matchingContainers"]] | Falso  a| 
Matriz JSON de objetos JSON de cada contêiner que corresponde aos critérios de correspondência configurados no aplicativo definido.



| matchingImages | array[string] | Falso  a| 
Array JSON contendo strings JSON para as imagens de contêiner correspondentes. Os valores definidos são:

* Itens mínimos: 0
* Máximo de itens: 4095
* Comprimento mínimo: 1
* Comprimento máximo: 255




| Ação | string | Verdadeiro  a| 
String JSON que indica qual ação o gancho de execução executará, caso os critérios de correspondência sejam atendidos. Os valores definidos são:

* "instantâneo"
* "backup"
* "restaurar"
* "failover"




| estágio | string | Verdadeiro  a| 
String JSON que indica o estágio da ação em que o gancho será executado. Os valores definidos são:

* "pre" - O gancho de execução será executado antes da ação especificada.
* "post" - O gancho de execução será executado após a ação especificada. Os valores para a ação "snapshot" são "pre" e "post". Os valores para a ação "backup" são "pre" e "post". O valor para a ação "restore" é "post". O valor para a ação "failover" é "post".




| hookSourceID | string | Verdadeiro  a| 
String JSON contendo o ID da origem do gancho que é executada por meio deste gancho de execução. Os valores definidos são:

* Conforme o esquema de identificador Astra




| argumentos | array[string] | Falso  a| 
Array JSON contendo strings JSON para os argumentos da fonte. Os valores definidos são:

* Itens mínimos: 0
* Máximo de itens: 16
* Comprimento mínimo: 0
* Comprimento máximo: 127




| ID do aplicativo | string | Falso  a| 
String JSON contendo o ID associado ao aplicativo ao qual este hook está vinculado. Essencialmente, outros critérios de correspondência, se definidos. Os valores definidos são:

* Conforme o esquema de identificador Astra




| habilitado | string | Verdadeiro  a| 
String JSON que indica se o gancho de execução está habilitado. Os valores definidos são:

* "true" - O gancho de execução está habilitado e será executado conforme especificado.
* "false" - O gancho de execução está desativado e nunca será executado. O valor padrão é "true".




| descrição | string | Falso  a| 
String JSON contendo uma descrição especificada pelo usuário para a origem do gancho. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 511




| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHook",
  "version": "1.3",
  "id": "5f7e2e31-280d-5984-a28b-2d19ab5b77c0",
  "name": "Payroll",
  "hookType": "custom",
  "matchingCriteria": [
    {
      "type": "podLabel",
      "value": "^env=production$"
    },
    {
      "type": "containerName",
      "value": "^payroll-master"
    }
  ],
  "matchingImages": [
    "docker.io/bitnami/payroll:3.7.8",
    "docker.io/bitnami/payroll:4.1.2"
  ],
  "matchingContainers": [
    {
      "namespaceName": "payroll-east",
      "podName": "payroll-release3-7",
      "podLabels": [
        {
          "name": "env",
          "value": "production"
        },
        {
          "name": "app.kubernetes.io/managed-by",
          "value": "Helm"
        }
      ],
      "containerName": "payroll-master-0",
      "containerImage": "docker.io/bitnami/payroll:3.7.8"
    },
    {
      "namespaceName": "payroll-east",
      "podName": "payroll-release3-7",
      "podLabels": [
        {
          "name": "env",
          "value": "production"
        },
        {
          "name": "app.kubernetes.io/managed-by",
          "value": "Helm"
        }
      ],
      "containerName": "payroll-master-1",
      "containerImage": "docker.io/bitnami/payroll:3.7.8"
    }
  ],
  "action": "snapshot",
  "stage": "pre",
  "hookSourceID": "50e89023-ba84-435d-bb47-1833f4c250ff",
  "arguments": [
    "freeze"
  ],
  "appID": "7be5ae7c-151d-4230-ac39-ac1d0b33c2a9",
  "enabled": "true",
  "description": "Payroll production hook",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
matchingCriteria

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
String JSON que identifica o tipo de critério de correspondência.



| valor | string | Verdadeiro  a| 
String JSON contendo uma expressão regular para corresponder ao tipo de correspondência fornecido. Sintaxe da expressão regular: https://github.com/google/re2/wiki/Syntax[]

|===
[role="api-collapsible-fifth-title"]
type_k8s_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
matchingContainers

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| podName | string | Falso  a| 
String JSON contendo o nome do pod do contêiner correspondente.



| podLabels | array[link:#type_k8s_label["type_k8s_label"]] | Falso  a| 
Matriz JSON de objetos de rótulos correspondentes aos rótulos do pod do contêiner.



| containerImage | string | Falso  a| 
String JSON da imagem correspondente ao contêiner.



| containerName | string | Falso  a| 
String JSON contendo o nome do contêiner correspondente.



| namespaceName | string | Falso  a| 
String JSON contendo o nome do namespace do pod do contêiner correspondente.

|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====