---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-ldapusers.html 
summary: Listar todos os usuários LDAP 
---
= Listar todos os usuários LDAP
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/ldapUsers`#

Retorna um array JSON de objetos JSON contendo os resultados da URL da requisição.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| incluir | string | consulta | Falso  a| 
Indica quais campos devem ser retornados ao listar uma coleção.

Exemplos de URL: "include=id", "include=id,name"

Exemplos OpenAPI: "id"

* exemplo: id,cn,dn




| limite | string | consulta | Falso  a| 
Indica o número máximo de recursos a serem retornados ao listar uma coleção.

Exemplos de URL: "limit=2"

Exemplos OpenAPI: "2"



| filtro | string | consulta | Falso  a| 
Indica quais campos devem ser correspondidos para retornar um recurso ao listar uma coleção.

Os operadores suportados são:

* eq - Igualdade
* lt/gt - Menor que/Maior que
* lte/gte - Menor ou igual a/Maior ou igual a


Exemplo de URL: "filter=field%20eq%20%27value%27"

Exemplos OpenAPI: "campo eq 'valor'"



| continuar |  | consulta | Falso  a| 
Indica o token a partir do qual a listagem será retomada.

Exemplos de URL: "continue=+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++

Exemplos OpenAPI: "+++<continue token="" from="" collection="" metadata="">+++"+++</continue>+++</continue>

|===


== Resposta

[source]
----
Status: 200, Returns a JSON array of JSON objects containing the results of the request URL.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| itens | array[Qualquer um de: link:#ldapUser_1_0_get_response_body["ldapUser_1.0_get_response_body"], array[]] | Verdadeiro  a| 



| metadados | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadeiro  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-ldapUsers",
  "version": "1.0",
  "items": [
    [
      "b4bcef18-14ad-5bc1-91ce-3cce15aa8791",
      "John Doe",
      "cn=John Doe,ou=people,dc=example,dc=com"
    ],
    [
      "98b10d6f-8693-555f-b258-70de4cc7301f",
      "Jane Doe",
      "cn=Jane Doe,ou=people,dc=example,dc=com"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/14",
  "title": "Unauthorized access",
  "detail": "The user isn't enabled.",
  "status": "403"
}
----
====


== Resposta

[source]
----
Status: 406, Not acceptable
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/32",
  "title": "Unsupported content type",
  "detail": "The response can't be returned in the requested format.",
  "status": "406"
}
----
====


== Resposta

[source]
----
Status: 500, Internal server error
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/34",
  "title": "Internal server error",
  "detail": "The server was unable to process this request.",
  "status": "500"
}
----
====


== Erro

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_metadados_astra

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Conforme o esquema de metadados Astra


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Verdadeiro  a| 



| CriaçãoTimestamp | string | Verdadeiro  a| 



| Alteração do Timestamp | string | Verdadeiro  a| 



| CreatedBy | string | Verdadeiro  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
ldapUser_1.0_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "aplicação/astra-ldapUser"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| e-mail | string | Falso  a| 
String JSON representando o e-mail do usuário LDAP. Os valores definidos são:

* Comprimento mínimo: 3
* Comprimento máximo: 63




| firstName | string | Falso  a| 
String JSON representando o primeiro nome do usuário LDAP. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| lastName | string | Falso  a| 
String JSON representando o sobrenome do usuário LDAP. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| cn | string | Falso  a| 
String JSON representando o nome do grupo LDAP. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| dn | string | Falso  a| 
String JSON que representa o nome diferenciado do grupo LDAP. Os valores definidos são:

* Em conformidade com RFC 4514




| metadados | link:#type_astra_metadata["tipo_metadados_astra"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Conforme o esquema de metadados Astra


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| continuar | string | Falso  a| 



| contar | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====