---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-buckets.html 
summary: Liste todos os buckets 
---
= Liste todos os buckets
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/buckets`#

Retorna uma matriz JSON com todos os recursos correspondentes na coleção. Se campos individuais forem especificados na solicitação, a matriz JSON de itens conterá os campos solicitados para cada recurso correspondente na ordem especificada.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}


|===


== Resposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| itens | array[Qualquer um de: link:#bucket_1_2_get_response_body["bucket_1.2_get_response_body"], array[]] | Verdadeiro  a| 



| metadados | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadeiro  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-buckets",
  "version": "1.2",
  "items": [
    [
      "4c753e39-25e9-4b36-a8de-69f168aa59cd",
      "Test Bucket",
      "gcp"
    ],
    [
      "d8fd585d-6429-4c08-a308-af193a88eac7",
      "Local",
      "ontap-s3"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
s3

Objeto JSON que fornece parâmetros do protocolo Simple Storage Service (S3). (Use este objeto para todos os provedores do tipo S3).

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| URL do servidor | string | Verdadeiro  a| 
String JSON contendo um URL para o caminho base do bucket. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 1023




| bucketName | string | Verdadeiro  a| 
String JSON contendo o nome do bucket S3. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63


|===
[role="api-collapsible-fifth-title"]
gcp

Objeto JSON que fornece parâmetros do protocolo Google Cloud.

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| bucketName | string | Verdadeiro  a| 
String JSON contendo o nome do bucket do Google Cloud que está sendo usado como base. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63


|===
[role="api-collapsible-fifth-title"]
azure

Objeto JSON que fornece parâmetros do protocolo Azure.

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| storageAccount | string | Verdadeiro  a| 
String JSON contendo o nome da conta de armazenamento do Azure. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63




| bucketName | string | Verdadeiro  a| 
String JSON contendo o nome do blob do Azure subjacente. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63


|===
[role="api-collapsible-fifth-title"]
bucketParameters

Objeto JSON que fornece informações específicas do provedor do bucket, necessárias para acessar o bucket. Os valores específicos neste bucket variam de acordo com o provedor.

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| s3 | link:#s3["s3"] | Falso  a| 
Objeto JSON que fornece parâmetros do protocolo Simple Storage Service (S3). (Use este objeto para todos os provedores do tipo S3).



| gcp | link:#gcp["gcp"] | Falso  a| 
Objeto JSON que fornece parâmetros do protocolo Google Cloud.



| azure | link:#azure["azure"] | Falso  a| 
Objeto JSON que fornece parâmetros do protocolo Azure.

|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
bucket_1.2_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-bucket"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"
* "1,2"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| nome | string | Verdadeiro  a| 
String JSON contendo um nome atribuído pelo usuário para o bucket. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 256




| ID da credencial | string | Verdadeiro  a| 
String JSON contendo o identificador das credenciais usadas para acessar o bucket. Os valores definidos são:

* Conforme o esquema de identificador Astra




| estado | string | Verdadeiro  a| 
String JSON contendo um valor que indica o estado operacional do bucket. Os valores definidos são:

* "Pendente" - O bucket está programado para descoberta
* "disponível" - O bucket está disponível para uso
* "failed" - O bucket está em estado de falha permanente
* "removido" - O bucket não está acessível no momento
* "desconhecido" - O estado do bucket não pode ser determinado




| stateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Verdadeiro  a| 
Matriz JSON de objetos JSON que lista detalhes adicionais sobre o motivo da transição do "state" para "removed" ou "failed". Se não houver detalhes disponíveis, essa matriz estará vazia.

* Itens mínimos: 0




| retentionTime | número | Falso  a| 
Número de segundos que representa o tempo durante o qual um arquivo neste bucket será retido. Os valores definidos são:

* -1 (Balde não suportado)
* 0 (sem política de retenção conhecida)
* 
+
[quote]
____
0 (Known política de retenção)

____





| provedor | string | Verdadeiro  a| 
String JSON que indica o protocolo do bucket que pode ser usado para acessar o bucket. Os valores definidos são:

* "ontap-s3"
* "storagegrid-s3"
* "generic-s3"
* "gcp"
* "azure"
* "aws"




| bucketParameters | link:#bucketParameters["bucketParameters"] | Verdadeiro  a| 
Objeto JSON que fornece informações específicas do provedor do bucket, necessárias para acessar o bucket. Os valores específicos neste bucket variam de acordo com o provedor.



| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| continuar | string | Falso  a| 



| contar | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====