---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-credentials-.html 
summary: Recuperar uma credencial 
---
= Recuperar uma credencial
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/credentials/{credential_id}`#

Retorna o recurso da API de credencial armazenado no corpo da resposta JSON.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| credencial_id | string | caminho | Verdadeiro  a| 
ID da coleção de credenciais a ser listada

|===


== Resposta

[source]
----
Status: 200, Returns the stored Credential API resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-credential"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| nome | string | Verdadeiro  a| 
String JSON contendo um nome especificado pelo usuário. Quando uma credencial é criada para um usuário, o nome será definido como o UUID desse usuário. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 127




| keyType | string | Falso  a| 
String JSON contendo um descritor de tipo de validação de dados opcional especificado pelo usuário para o conteúdo do keyStore. Restrições de atualização estendidas:

* Se um keyType não existir no recurso e não for especificado em uma atualização, o keyType não deverá continuar a existir no recurso atualizado.
* Se um keyType não existir no recurso e for especificado em uma atualização, o keyType deverá ser adicionado ao recurso e a validação deverá ser realizada. Se a validação falhar, a atualização falhará.
* Se um keyType existir no recurso e não for especificado em uma atualização, o keyType deve ser preservado.
* Se um keyType existir no recurso e for especificado em uma atualização, e o keyType especificado corresponder ao keyType existente, o keyType deve ser preservado.
* Se um keyType existir no recurso e for especificado em uma atualização, e o keyType especificado for diferente do keyType existente, a atualização falhará. Os valores definidos são:
* "genérico" - A credencial é uma coleção genérica de dados. Isso é equivalente a não incluir um keyType.
* A validação estendida é realizada da seguinte forma:
* Uma ou mais strings devem existir no keyStore.
* Cada string no keyStore deve ter um valor codificado em base64.
* "passwordHash" - A credencial é um hash de senha.
* A validação estendida é realizada da seguinte forma:
* O nome da credencial deve ser único.
* O nome da credencial deve ser igual a um ID de recurso de usuário válido.
* O nome da credencial não deve ser alterado.
* O recurso de usuário correspondente deve ter um "authProvider" de "local".
* Deve existir uma string "texto claro" dentro do keyStore com um valor contendo uma senha em texto claro codificada em base64:
* A senha em texto simples deve estar em conformidade com a política de senhas da conta.
* A senha é armazenada como um hash.
* Deve existir uma string "change" dentro do keyStore com um valor contendo uma string codificada em base64 "true" ou "false".
* Uma credencial do tipo passwordHash só pode ser excluída se o ID do usuário indicado pelo nome não existir.
* "apikey" - A credencial é uma chave de API.
* A validação estendida é realizada da seguinte forma:
* Deve existir uma string "apikey" dentro do keyStore, com um valor contendo uma string arbitrária codificada em base64.
* "kubeconfig" - A credencial é um kubeconfig.
* A validação estendida é realizada da seguinte forma:
* Deve existir uma string "base64" dentro do keyStore, com um valor contendo um arquivo kubeconfig JSON codificado em base64.
* O arquivo kubeconfig deve descrever apenas um único cluster.
* Não podem existir outros campos dentro do keyStore.
* "certificado" - A credencial é um certificado codificado em PEM
* A validação estendida é realizada da seguinte forma:
* Deve existir uma string de "certificate" dentro do keyStore, com um valor contendo um certificado PEM codificado em base64.
* "privkey" - A credencial é uma chave privada codificada em PEM.
* A validação estendida é realizada da seguinte forma:
* Deve existir uma string "privkey" dentro do keyStore, com um valor contendo uma chave privada PEM codificada em base64.
* "s3" - Indica que as credenciais são para acesso ao Simple Storage Service (S3).
* A validação estendida é realizada da seguinte forma:
* Uma string ""accessKey"" deve existir dentro do keyStore com um valor contendo uma chave de acesso S3 codificada em base64.
* Uma string ""accessSecret"" deve existir dentro do keyStore com um valor contendo um segredo de acesso S3 codificado em base64.




| válido | string | Verdadeiro  a| 
String JSON que descreve se a credencial é válida para uso. Valor padrão, se omitido, é "true". Os valores definidos são:

* "verdadeiro" - A credencial está apta para uso.
* "falso" - A credencial não deve ser usada.




| validFromTimestamp | string | Falso  a| 
String JSON contendo um carimbo de data/hora indicando quando a credencial é válida. Esses registros são usados para rotação de credenciais. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| validUntilTimestamp | string | Falso  a| 
String JSON contendo um registro de data e hora indicando quando a credencial deixa de ser válida. Esses registros são usados para rotação de credenciais. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-credential",
  "version": "1.1",
  "id": "58e26f6a-a631-5122-8e0e-7afe306675c0",
  "name": "myCert",
  "valid": "true",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====