---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-appmirrors.html 
summary: Liste os recursos AppMirror de um aplicativo 
---
= Liste os recursos AppMirror de um aplicativo
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appMirrors`#

Retorna uma matriz JSON com todos os recursos correspondentes na coleção. Se campos individuais forem especificados na solicitação, a matriz JSON de itens conterá os campos solicitados para cada recurso correspondente na ordem especificada.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| app_id | string | caminho | Verdadeiro  a| 
ID do recurso do aplicativo que o contém



| incluir | string | consulta | Falso  a| 
Indica quais campos devem ser retornados ao listar uma coleção.

Exemplos de URL: "include=id", "include=id,name"

Exemplos OpenAPI: "id"



| limite | string | consulta | Falso  a| 
Indica o número máximo de recursos a serem retornados ao listar uma coleção.

Exemplos de URL: "limit=2"

Exemplos OpenAPI: "2"



| filtro | string | consulta | Falso  a| 
Indica quais campos devem ser correspondidos para retornar um recurso ao listar uma coleção.

Os operadores suportados são:

* eq - Igualdade
* lt/gt - Menor que/Maior que
* lte/gte - Menor ou igual a/Maior ou igual a


Exemplo de URL: "filter=field%20eq%20%27value%27"

Exemplos OpenAPI: "campo eq 'valor'"

|===


== Resposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| itens | array[Qualquer um de: link:#appMirror_1_1_get_response_body["appMirror_1.1_get_response_body"], array[]] | Verdadeiro  a| 



| metadados | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadeiro  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appMirrors",
  "version": "1.1",
  "items": [
    {
      "type": "application/astra-appMirror",
      "version": "1.1",
      "id": "f1c98c2e-6391-42d3-8b21-3e75dac048a3",
      "sourceAppID": "efd639b6-fc92-4112-8841-0c0ab7890ae0",
      "sourceClusterID": "5789e026-c2e2-41e9-ab00-9766bcfa8951",
      "destinationAppID": "cd7b6d91-fc19-4983-a754-9a7bb4d80a7b",
      "destinationClusterID": "c5d023a9-4061-4a8a-bfbf-3be11ff06226",
      "namespaceMapping": [
        {
          "clusterID": "5789e026-c2e2-41e9-ab00-9766bcfa8951",
          "namespaces": [
            "ns1-src",
            "ns2-src"
          ]
        },
        {
          "clusterID": "c5d023a9-4061-4a8a-bfbf-3be11ff06226",
          "namespaces": [
            "ns1-dest",
            "ns2-dest"
          ]
        }
      ],
      "state": "established",
      "stateTransitions": [
        {
          "from": "establishing",
          "to": [
            "established",
            "deleting"
          ]
        },
        {
          "from": "established",
          "to": [
            "failingOver",
            "deleting"
          ]
        },
        {
          "from": "failingOver",
          "to": [
            "failedOver",
            "deleting"
          ]
        },
        {
          "from": "failedOver",
          "to": [
            "establishing",
            "deleting"
          ]
        },
        {
          "from": "deleting",
          "to": [
            "deleted"
          ]
        }
      ],
      "stateDesired": "established",
      "stateAllowed": [
        "failedOver",
        "deleted"
      ],
      "stateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/1",
          "title": "AppMirror relationship established",
          "detail": "The AppMirror relationship has been successfully established."
        }
      ],
      "healthState": "normal",
      "healthStateTransitions": [
        {
          "from": "indeterminate",
          "to": [
            "normal",
            "warning",
            "critical"
          ]
        },
        {
          "from": "normal",
          "to": [
            "indeterminate",
            "warning",
            "critical"
          ]
        },
        {
          "from": "warning",
          "to": [
            "indeterminate",
            "normal",
            "critical"
          ]
        },
        {
          "from": "critical",
          "to": [
            "indeterminate",
            "normal",
            "warning"
          ]
        }
      ],
      "healthStateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/2",
          "title": "SnapMirror syncing successfully",
          "detail": "All SnapMirror relationships are synchronizing as expected."
        }
      ],
      "metadata": {
        "labels": [],
        "creationTimestamp": "2020-08-06T12:24:52.256624Z",
        "modificationTimestamp": "2020-08-06T12:24:52.256624Z",
        "createdBy": "11c0cfa1-4f27-4ef7-a21c-cb452fc5c9aa"
      }
    },
    {
      "type": "application/astra-appMirror",
      "version": "1.1",
      "id": "114633f0-5b59-4bd7-adce-a9ba4423a1bd",
      "sourceAppID": "eaf8b854-211d-460a-ac18-d093d8e2ac70",
      "sourceClusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
      "destinationAppID": "e829c5e0-750f-44ad-a684-aee85be2c2bb",
      "destinationClusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
      "namespaceMapping": [
        {
          "clusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
          "namespaces": [
            "app-namespace"
          ],
          "role": "source"
        },
        {
          "clusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
          "namespaces": [
            "destination-app-namespace"
          ],
          "role": "destination"
        }
      ],
      "storageClasses": [
        {
          "storageClassName": "destination-sc",
          "clusterID": "fcb27b51-ebb7-40ca-b8f1-1d23ebd06889",
          "role": "destination"
        }
      ],
      "state": "established",
      "stateTransitions": [
        {
          "from": "establishing",
          "to": [
            "established",
            "deleting"
          ]
        },
        {
          "from": "established",
          "to": [
            "failingOver",
            "deleting"
          ]
        },
        {
          "from": "failingOver",
          "to": [
            "failedOver",
            "deleting"
          ]
        },
        {
          "from": "failedOver",
          "to": [
            "establishing",
            "deleting"
          ]
        }
      ],
      "stateDesired": "established",
      "stateAllowed": [
        "failedOver",
        "deleted"
      ],
      "stateDetails": [],
      "transferState": "idle",
      "transferStateTransitions": [
        {
          "from": "transferring",
          "to": [
            "idle"
          ]
        },
        {
          "from": "idle",
          "to": [
            "transferring"
          ]
        }
      ],
      "transferStateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/24",
          "title": "Snapshot replication completed",
          "detail": "A snapshot was replicated to the destination.",
          "additionalDetails": {
            "completionTime": "2023-07-06T22:46:39Z",
            "snapshotID": "ae60820d-e963-4eab-8bb3-9159e9f012f0",
            "startTime": "2023-07-06T22:46:08Z"
          }
        }
      ],
      "healthState": "normal",
      "healthStateTransitions": [],
      "healthStateDetails": [
        {
          "type": "https://astra.netapp.io/stateDetails/24",
          "title": "Snapshot replication completed",
          "detail": "A snapshot was replicated to the destination.",
          "additionalDetails": {
            "completionTime": "2023-07-06T22:46:39Z",
            "snapshotID": "ae60820d-e963-4eab-8bb3-9159e9f012f0",
            "startTime": "2023-07-06T22:46:08Z"
          }
        }
      ],
      "metadata": {
        "labels": [],
        "creationTimestamp": "2023-07-06T22:45:24Z",
        "modificationTimestamp": "2023-07-06T22:45:24Z",
        "createdBy": "cc420827-f968-4da7-9e72-df8a0fd52f94"
      }
    }
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
namespaceMapping

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| ID do cluster | string | Falso  a| 
Identificador do cluster para o qual os namespaces são especificados. Os valores definidos são:

* Conforme o esquema de identificador Astra




| espaços de nomes | array[string] | Falso  a| 
Lista de namespaces a serem usados no cluster. Correlacionada com a lista de namespaces de outro cluster por índice. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63
* Em conformidade com o esquema de rótulos DNS 1123




| papel | string | Falso  a| 
A função inicial para esta definição de namespace. Este parâmetro é opcional, exceto quando uma configuração de replicação no mesmo cluster é utilizada. Os valores definidos são:

* "fonte"
* "destino"


|===
[role="api-collapsible-fifth-title"]
storageClasses

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| ID do cluster | string | Falso  a| 
Identificador do cluster para o qual a classe de armazenamento está especificada. Os valores definidos são:

* Conforme o esquema de identificador Astra




| storageClassName | string | Falso  a| 
Nome da classe de armazenamento a ser usada ao criar PVCs no cluster especificado em "clusterID". Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 255




| papel | string | Falso  a| 
A função inicial para esta definição de classe de armazenamento. Este parâmetro é opcional, exceto quando uma configuração de replicação no mesmo cluster é utilizada. Os valores definidos são:

* "fonte"
* "destino"


|===
[role="api-collapsible-fifth-title"]
type_astra_stateTransition

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| de | string | Verdadeiro  a| 



| para | array[string] | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
appMirror_1.1_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "aplicação/astra-appMirror"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| ID do aplicativo de origem | string | Verdadeiro  a| 
Identificador do aplicativo de origem. Atualizado somente quando o sourceAppID é trocado pelo destinationAppID. Os valores definidos são:

* Conforme o esquema de identificador Astra




| ID do cluster de origem | string | Verdadeiro  a| 
Identificador do cluster gerenciado que hospeda o aplicativo de origem. Este campo é somente leitura e é determinado com base no cluster host do aplicativo de origem. Se fornecido em uma atualização, ele deve corresponder ao ID do cluster do aplicativo de origem, portanto, só pode ser alterado ao trocar o sourceAppID pelo destinationAppID. Os valores definidos são:

* Conforme o esquema de identificador Astra




| ID do aplicativo de destino | string | Falso  a| 
Identificador do aplicativo de destino. Não pode ser fornecido na criação, pois um novo ID de aplicativo será gerado como parte da inicialização do relacionamento. Só pode ser atualizado ao trocar sourceAppID pelo destinationAppID. Os valores definidos são:

* Conforme o esquema de identificador Astra




| ID do cluster de destino | string | Verdadeiro  a| 
Identificador do cluster gerenciado que hospedará o aplicativo de destino. Deve ser fornecido na criação, pois determina em qual cluster o aplicativo de destino será criado. Se fornecido na atualização, deve corresponder ao ID do cluster de destino do aplicativo de destino, portanto, só pode ser alterado ao trocar sourceAppID por destinationAppID. Os valores definidos são:

* Conforme o esquema de identificador Astra




| namespaceMapping | array[link:#namespaceMapping["namespaceMapping"]] | Falso  a| 
O namespace ou namespaces a serem usados ao criar o aplicativo de destino, correspondentes aos namespaces do aplicativo de origem. Cada objeto JSON contém os campos "clusterID" e "namespaces", onde o valor de "clusterID" é a string JSON que identifica o cluster de origem ou de destino, e o valor de "namespaces" é um array JSON de strings JSON. Deve haver exatamente um objeto JSON para cada cluster, e os namespaces serão correlacionados por índice. Se não forem fornecidos, o mesmo namespace do cluster de origem será usado no cluster de destino. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 2




| storageClasses | array[link:#storageClasses["storageClasses"]] | Falso  a| 
A classe de armazenamento a ser usada no cluster de destino ao criar novas Persistent Volume Claims (PVCs). Cada objeto JSON contém os campos "clusterID" e "storageClassName", onde o valor "clusterID" é o ID em formato de string JSON do cluster de origem ou cluster de destino, e o "storageClassName" é a classe de armazenamento a ser usada ao criar PVCs nesse cluster. Se não for fornecido ou se o valor estiver ausente para um cluster, a classe de armazenamento padrão será usada para esse cluster. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 2




| estado | string | Verdadeiro  a| 
O estado do relacionamento. Os valores definidos são:

* "Estabelecendo" - O relacionamento está sendo criado.
* "established" - O relacionamento está criado.
* "failingOver" - A transferência da aplicação para o cluster de destino está em andamento.
* "failedOver" - O failover da aplicação para o cluster de destino foi concluído.
* "Excluindo" - Os recursos criados pelo relacionamento estão sendo limpos.
* "Excluído" - O relacionamento foi limpo e excluído.




| stateTransitions | array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Falso  a| 
Transições de estado permitidas. As seguintes transições de estado são possíveis para este recurso:

* "estabelecendo": "estabelecido", "excluindo"
* "estabelecido": "failingOver", "excluindo"
* "failingOver": "failedOver", "excluindo"
* "failedOver": "estabelecendo", "excluindo"
* "excluindo": "excluído"
* "excluído":




| stateDesired | string | Verdadeiro  a| 
O estado desejado para o relacionamento. Na criação, o único valor válido é "estabelecido". Os valores definidos são:

* "established" - O relacionamento está criado.
* "failedOver" - O failover da aplicação para o cluster de destino foi concluído.
* "Excluído" - O relacionamento foi limpo e excluído com sucesso.




| stateAllowed | array[string] | Falso  a| 
Estados que podem ser solicitados em um determinado estado. Os seguintes estados podem ser solicitados em cada estado definido:

* "estabelecendo": "estabelecido", "excluído"
* "estabelecido": "failedOver", "excluído"
* "failingOver": "failedOver", "excluído"
* "failedOver": "estabelecido", "excluído"
* "excluindo": "excluído"
* "excluído": "excluído"




| stateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Verdadeiro  a| 
Detalhes adicionais sobre o estado atual, incluindo o motivo pelo qual esse estado foi alcançado. Se não houver detalhes disponíveis, essa matriz estará vazia. Os valores definidos são:

* Quantidade mínima de itens: 0




| transferState | string | Falso  a| 
Estado da transferência de instantâneo atual ou mais recente. Os valores definidos são:

* "Transferindo" - Um novo snapshot foi criado e está sendo replicado para o cluster de destino. Este estado também abrange as transferências que falharam em tentativas anteriores e estão sendo continuamente repetidas.
* "idle" - Não há nenhuma transferência em andamento no momento.




| transferStateTransitions | array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Falso  a| 
Transições de estado permitidas a partir de um determinado estado definido. As seguintes transições de estado são possíveis para este recurso:

* "transferindo": "ocioso"
* "ocioso": "transferindo"




| transferStateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falso  a| 
Detalhes adicionais sobre o estado atual, incluindo o motivo pelo qual esse estado foi alcançado. Se não houver detalhes disponíveis, essa matriz estará vazia. Os valores definidos são:

* Quantidade mínima de itens: 0




| healthState | string | Verdadeiro  a| 
Estado de saúde do recurso. Os valores definidos são:

* "Indeterminado" - O estado de saúde do recurso não pode ser determinado (por exemplo, devido à falta de conectividade)
* "normal" - O recurso não apresenta problemas conhecidos e pode fornecer serviços de acordo com a especificação da interface
* "Aviso" - O recurso apresenta problemas conhecidos que não o impedem de fornecer serviços de acordo com a especificação da interface
* "Crítico" - O recurso apresenta problemas conhecidos que o impedem de fornecer serviços de acordo com a especificação da interface




| healthStateTransitions | array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Verdadeiro  a| 
Transições de estado permitidas a partir de um determinado estado definido. As seguintes transições de estado são possíveis para este recurso:

* "indeterminado": "normal", "aviso", "crítico"
* "normal": "indeterminado", "aviso", "crítico"
* "aviso": "indeterminado", "normal", "crítico"
* "crítico": "indeterminado", "normal", "aviso"




| healthStateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Verdadeiro  a| 
Detalhes adicionais sobre o estado atual, incluindo o motivo pelo qual esse estado foi alcançado. Se não houver detalhes disponíveis, essa matriz estará vazia. Os valores definidos são:

* Quantidade mínima de itens: 0




| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| continuar | string | Falso  a| 



| contar | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====