---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-appsnaps.html 
summary: Liste os snapshots do aplicativo para um app 
---
= Liste os snapshots do aplicativo para um app
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appSnaps`#

Retorna uma matriz JSON com todos os recursos correspondentes na coleção. Se campos individuais forem especificados na solicitação, a matriz JSON de itens conterá os campos solicitados para cada recurso correspondente na ordem especificada.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| app_id | string | caminho | Verdadeiro  a| 
ID do recurso do aplicativo que o contém



| incluir | string | consulta | Falso  a| 
Indica quais campos devem ser retornados ao listar uma coleção.

Exemplos de URL: "include=id", "include=id,name"

Exemplos OpenAPI: "id"

* exemplo: id, nome, estado




| limite | string | consulta | Falso  a| 
Indica o número máximo de recursos a serem retornados ao listar uma coleção.

Exemplos de URL: "limit=2"

Exemplos OpenAPI: "2"

|===


== Resposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| itens | array[Qualquer um de: link:#appSnap_1_2_get_response_body["appSnap_1.2_get_response_body"], array[]] | Verdadeiro  a| 



| metadados | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadeiro  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appSnaps",
  "version": "1.2",
  "items": [
    [
      "2b6dafc3-2172-4431-a482-6306b2703130",
      "app-name-245",
      "pending"
    ],
    [
      "6fd9b31a-3924-4c9a-878b-175fa9538b8c",
      "app-name-244",
      "completed"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_metadados_astra

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Verdadeiro  a| 



| CriaçãoTimestamp | string | Verdadeiro  a| 



| Alteração do Timestamp | string | Verdadeiro  a| 



| CreatedBy | string | Verdadeiro  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
appSnap_1.2_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "aplicação/astra-appSnap"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"
* "1,2"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| nome | string | Verdadeiro  a| 
String JSON contendo um nome especificado pelo usuário para o Snapshot. Se não for especificado, ou quando Snapshots forem iniciados por um agendamento, o sistema atribui um nome para o Snapshot. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63
* Em conformidade com o esquema de rótulos DNS 1123




| ID do agendamento | string | Falso  a| 
String JSON contendo um ID de agendamento opcional que indica que o snapshot foi acionado por um agendamento e especifica qual agendamento acionou o snapshot. Presente apenas para snapshots iniciados por um agendamento. Os valores definidos são:

* Conforme o esquema de identificador Astra




| snapshotAppAsset | string | Falso  a| 
String JSON contendo o ID do recurso do aplicativo correspondente ao snapshot. Este campo será retornado quando o estado do snapshot do aplicativo for "completed". Os valores definidos são:

* Conforme o esquema de identificador Astra




| estado | string | Verdadeiro  a| 
String JSON contendo um valor que indica o estado operacional do snapshot. Os valores definidos são:

* "Pendente" - O Snapshot do aplicativo está agendado para descoberta
* "Descobrindo" - O Snapshot do aplicativo está em processo de descoberta
* "Em execução" - O Snapshot do aplicativo está em execução normalmente
* "Concluído" - O Snapshot do aplicativo foi concluído
* "failed" - O Snapshot do aplicativo está em estado de falha permanente
* "Removido" - O Snapshot do aplicativo não está acessível no momento
* "Desconhecido" - Não foi possível determinar o estado do Snapshot do aplicativo




| stateUnready | array[string] | Verdadeiro  a| 
Matriz JSON de strings JSON, cada uma indicando um motivo pelo qual um snapshot de aplicativo não consegue passar para o estado "em execução" ou pelo qual passou para o estado "com falha". Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 127




| hookState | string | Falso  a| 
String JSON contendo um valor que indica o estado de qualquer gancho de execução ou ganchos em execução como parte de um snapshot. Os valores definidos são:

* "failed" - Um ou mais ganchos de execução falharam
* "Sucesso" - Havia zero ou mais ganchos aplicáveis e todos foram bem-sucedidos




| hookStateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falso  a| 
Matriz JSON de objetos JSON que lista detalhes adicionais sobre o motivo pelo qual "hookState" foi transferido para "falhou". Se não houver detalhes disponíveis, essa matriz estará vazia.

* Itens mínimos: 0




| metadados | link:#type_astra_metadata["tipo_metadados_astra"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| continuar | string | Falso  a| 



| contar | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====