---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-packages.html 
summary: Liste todos os pacotes 
---
= Liste todos os pacotes
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/packages`#

Retorna uma matriz JSON com todos os recursos correspondentes na coleção. Se campos individuais forem especificados na solicitação, a matriz JSON de itens conterá os campos solicitados para cada recurso correspondente na ordem especificada.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| filtro | string | consulta | Falso  a| 
Indica quais campos devem ser correspondidos para retornar um recurso ao listar uma coleção.

Os operadores suportados são:

* eq - Igualdade
* lt/gt - Menor que/Maior que
* lte/gte - Menor ou igual a/Maior ou igual a


Exemplo de URL: "filter=field%20eq%20%27value%27"

Exemplos OpenAPI: "campo eq 'valor'"



| Ordenar | string | consulta | Falso  a| 
Indica a ordem de classificação dos recursos ao listar uma coleção.

Exemplos de URL: "orderBy=name", "orderBy=name%20desc"

Exemplos OpenAPI: "nome desc"



| incluir | string | consulta | Falso  a| 
Indica quais campos devem ser retornados ao listar uma coleção.

Exemplos de URL: "include=id", "include=id,name"

Exemplos OpenAPI: "id"

* exemplo: id,packageName,packageVersion,softwareType




| limite | string | consulta | Falso  a| 
Indica o número máximo de recursos a serem retornados ao listar uma coleção.

Exemplos de URL: "limit=2"

Exemplos OpenAPI: "2"

|===


== Resposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| itens | array[Qualquer um de: link:#package_1_0_get_response_body["pacote_1.0_obter_corpo_da_resposta"], array[]] | Verdadeiro  a| 



| metadados | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadeiro  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-packages",
  "version": "1.0",
  "items": [
    [
      "e280ff62-be35-4f31-a31b-a210a1ad1b33",
      "acc",
      "22.01.0",
      "install"
    ],
    [
      "e8507dad-d33f-44b3-9c15-ec55ba6f6473",
      "acc",
      "22.01.1",
      "patch"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
type_astra_stateTransition

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| de | string | Verdadeiro  a| 



| para | array[string] | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
dependsOnImages

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| imagePath | string | Verdadeiro  a| 
String JSON contendo o caminho para esta imagem Docker. Não deve conter o nome do registro, apenas o caminho absoluto da raiz até a imagem. Exemplo: /globalcicd/acc Valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 1023




| imageName | string | Verdadeiro  a| 
String JSON contendo o nome da imagem Docker. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| imageTag | string | Verdadeiro  a| 
String JSON representando a tag/versão desta imagem. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 31


|===
[role="api-collapsible-fifth-title"]
imagens

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| imageName | string | Verdadeiro  a| 
String JSON contendo o nome da imagem Docker. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| imagePath | string | Verdadeiro  a| 
String JSON contendo o caminho para esta imagem Docker. Não deve conter o nome do registro, apenas o caminho absoluto da raiz até a imagem. Exemplo: /globalcicd/acc Valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 1023




| imageTag | string | Verdadeiro  a| 
String JSON representando a tag/versão desta imagem. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 31




| imageDigest | string | Verdadeiro  a| 
String JSON representando o resumo desta imagem. Os valores definidos são:

* A expressão regular definida é: "^(sha256:)[0-9a-f]{64}$"




| dependsOnImages | array[link:#dependsOnImages["dependsOnImages"]] | Falso  a| 
Matriz JSON de objetos JSON que descrevem as imagens necessárias para instalar ou atualizar a imagem atual.

|===
[role="api-collapsible-fifth-title"]
dependsOnComponents

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| componentName | string | Verdadeiro  a| 
String JSON que descreve o nome do componente. Os valores definidos são:

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| versões | array[string] | Verdadeiro  a| 
Matriz JSON de strings JSON que definem a versão do componente necessária para instalar a imagem atual.

|===
[role="api-collapsible-fifth-title"]
artefatos

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| artifactName | string | Verdadeiro  a| 
String JSON contendo o nome do arquivo. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| artifactIdentifier | string | Verdadeiro  a| 
String JSON contendo um identificador para este arquivo. Entre versões do mesmo tipo de pacote, o nome do arquivo pode mudar, mas o identificador geralmente permanece o mesmo. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 511




| artifactPath | string | Verdadeiro  a| 
String JSON contendo o caminho para este artefato a partir da raiz de um Astra Control Center Data Store/local conhecido. Exemplo: /vmware/1.0/ Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 1023




| artifactVersion | string | Falso  a| 
String JSON contendo a versão do artefato, se fornecida. Os valores definidos são:

* Está em conformidade com o SemVer Schema
* Comprimento mínimo: 1
* Comprimento máximo: 31




| dependsOnComponents | array[link:#dependsOnComponents["dependsOnComponents"]] | Falso  a| 
Matriz JSON de objetos JSON que descrevem os componentes instalados necessários para instalar/atualizar a imagem atual.

|===
[role="api-collapsible-fifth-title"]
arquivos

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| fileName | string | Verdadeiro  a| 
String JSON contendo o nome do arquivo. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| fileIdentifier | string | Verdadeiro  a| 
String JSON contendo um identificador deste arquivo. Entre versões do mesmo tipo de pacote, o nome do arquivo pode mudar, mas o identificador geralmente permanece o mesmo. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 511




| fileMediaType | string | Verdadeiro  a| 
String JSON contendo o tipo de mídia do arquivo. Os valores definidos são quaisquer tipos de mídia definidos por https://www.iana.org/assignments/media-types/media-types.xhtml["IANA"]. Além disso, application/x-yaml ou application/x-yaml para arquivos yaml são suportados.

* Comprimento mínimo: 1
* Comprimento máximo: 211




| fileContents | string | Verdadeiro  a| 
String JSON contendo o conteúdo do arquivo. Os valores definidos são:

* Em conformidade com o esquema Base64 FIXME - Como especificamos que isto está comprimido? Qual algoritmo, etc?


|===
[role="api-collapsible-fifth-title"]
upgradableVersions

Objeto JSON contendo as versões mínima e máxima que podem ser atualizadas para a versão do pacote.

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| minVersion | string | Falso  a| 
String JSON que descreve a versão mínima que pode ser atualizada para a versão do pacote. Os valores definidos são:

* Está em conformidade com o SemVer Schema




| maxVersion | string | Falso  a| 
String JSON que descreve a versão máxima para a qual o pacote pode ser atualizado. Os valores definidos são:

* Está em conformidade com o SemVer Schema


|===
[role="api-collapsible-fifth-title"]
dependências

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| componentName | string | Verdadeiro  a| 
String JSON que descreve o nome do componente. Os valores definidos são:

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| componentMinVersion | string | Falso  a| 
String JSON que descreve a versão mínima necessária para esse componente. Os valores definidos são:

* Está em conformidade com o SemVer Schema




| componentMaxVersion | string | Falso  a| 
String JSON que descreve a versão máxima necessária para esse componente. Os valores definidos são:

* Está em conformidade com o SemVer Schema


|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_metadados_astra

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Verdadeiro  a| 



| CriaçãoTimestamp | string | Verdadeiro  a| 



| Alteração do Timestamp | string | Verdadeiro  a| 



| CreatedBy | string | Verdadeiro  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
pacote_1.0_obter_corpo_da_resposta

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-package"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| packageName | string | Verdadeiro  a| 
String JSON contendo o nome do pacote. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 31 Exemplos de valores são:
* "acc"
* "acs"
* "Trident"




| packageVersion | string | Verdadeiro  a| 
String JSON contendo o SemVer do pacote. Os valores definidos são:

* Está em conformidade com o SemVer Schema




| packageType | string | Verdadeiro  a| 
String JSON contendo o tipo de pacote, indicando se é um pacote de instalação completo ou um patch. Os valores definidos são:

* "instalar"
* "correção"




| bundleName | array[string] | Falso  a| 
Array JSON de strings JSON contendo o nome do bundle no qual o pacote está contido.



| severityLevel | string | Verdadeiro  a| 
String JSON que descreve o nível de severidade desta correção ou instalação. Os valores definidos são:

* "recomendado" - A instalação é recomendada - Valor padrão
* "crítico" - A instalação é altamente recomendada para corrigir erros críticos e/ou patches de segurança




| packageState | string | Verdadeiro  a| 
String JSON contendo um valor que indica o estado operacional do pacote. Após a verificação do pacote e após a importação, o estado indicará "completo". Caso contrário, o estado indicará "incompleto". Os valores definidos são:

* "Verificando" - O pacote está em processo de validação
* "corrompido" - O pacote está corrompido
* "incompleto" - O pacote está faltando elementos
* "Disponível" - Todos os elementos associados ao pacote estão disponíveis e o pacote está pronto para uso




| packageStateTransitions | array[link:#type_astra_stateTransition["type_astra_stateTransition"]] | Verdadeiro  a| 
Matriz JSON de objetos JSON, cada um representando o conjunto de transições de estado permitidas a partir de um determinado estado definido. Cada objeto JSON contém os campos "from" e "to", onde o valor de "from" é o nome de um estado e o valor de "to" é uma matriz de estados de destino permitidos. Os valores definidos são:

* Está em conformidade com o Esquema de Transição de Estado




| packageStateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Verdadeiro  a| 
Matriz JSON de objetos JSON que lista detalhes adicionais sobre o "estado" atual. Se não houver detalhes disponíveis, essa matriz estará vazia.

* Quantidade mínima de itens: 0




| imagens | array[link:#images["imagens"]] | Falso  a| 
Matriz JSON de objetos JSON, cada um contendo uma imagem Docker que faz parte do pacote.



| artefatos | array[link:#artifacts["artefatos"]] | Falso  a| 
Matriz JSON de objetos JSON que descrevem os artefatos adicionais (binários e outros) associados a este pacote.



| arquivos | array[link:#files["arquivos"]] | Falso  a| 
Matriz JSON de objetos JSON, cada um representando um artefato não imagem associado a este pacote.



| upgradableVersions | link:#upgradableVersions["upgradableVersions"] | Falso  a| 
Objeto JSON contendo as versões mínima e máxima que podem ser atualizadas para a versão do pacote.



| dependências | array[link:#dependencies["dependências"]] | Falso  a| 
Matriz JSON de objetos JSON que descreve qual versão mínima de uma determinada dependência é necessária para que este pacote seja instalado



| metadados | link:#type_astra_metadata["tipo_metadados_astra"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| continuar | string | Falso  a| 



| contar | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====