---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-licenses.html 
summary: Liste todas as licenças 
---
= Liste todas as licenças
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/licenses`#

Retorna uma matriz JSON com todos os recursos correspondentes na coleção. Se campos individuais forem especificados na solicitação, a matriz JSON de itens conterá os campos solicitados para cada recurso correspondente na ordem especificada.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| incluir | string | consulta | Falso  a| 
Indica quais campos devem ser retornados ao listar uma coleção.

Exemplos de URL: "include=id", "include=id,name"

Exemplos OpenAPI: "id"

* exemplo: id,produto




| limite | string | consulta | Falso  a| 
Indica o número máximo de recursos a serem retornados ao listar uma coleção.

Exemplos de URL: "limit=2"

Exemplos OpenAPI: "2"



| filtro | string | consulta | Falso  a| 
Indica quais campos devem ser correspondidos para retornar um recurso ao listar uma coleção.

Os operadores suportados são:

* eq - Igualdade
* lt/gt - Menor que/Maior que
* lte/gte - Menor ou igual a/Maior ou igual a


Exemplo de URL: "filter=field%20eq%20%27value%27"

Exemplos OpenAPI: "campo eq 'valor'"

|===


== Resposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| itens | array[Qualquer um de: link:#license_1_0_get_response_body["license_1.0_get_response_body"], array[]] | Verdadeiro  a| 



| metadados | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadeiro  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-licenses",
  "version": "1.0",
  "items": [
    [
      "c8aa757a-5318-489f-8134-a2a1a6956a3e",
      "Astra SDS"
    ],
    [
      "0f7cc03d-9afc-4192-af7f-b29ab24f8f2a",
      "Astra Enterprise"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
complementos

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| startDate | string | Falso  a| 
String JSON contendo um carimbo de data/hora indicando quando este complemento se torna válido. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| endDate | string | Falso  a| 
String JSON contendo um carimbo de data/hora indicando quando este complemento deixa de ser válido. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| características | string | Falso  a| 
String JSON contendo a lista de funcionalidades associadas a este complemento. Os valores definidos são:

* O conteúdo da string não foi validado pelo esquema.




| capacidade | string | Falso  a| 
String JSON contendo a capacidade extraída do complemento. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| licenseProtocol | string | Falso  a| 
String JSON contendo o protocolo de licença associado a este complemento. Os valores definidos são:

* Conteúdo da string não validado pelo esquema


|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
license_1.0_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-license"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| alocação | string | Falso  a| 
String JSON contendo um ID que indica a que a licença está alocada. Presente somente quando a licença está alocada. Para licenças do Astra Control Center, este campo deve ser preenchido com o ID da conta e deve corresponder ao ID da conta especificado no URI POST. Os valores definidos são:

* Conforme o esquema de identificador Astra




| ID do host | string | Falso  a| 
String JSON contendo um identificador de host ao qual uma licença está vinculada. Presente apenas se a licença estiver vinculada a um host específico. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| ID de credenciais do dispositivo | string | Falso  a| 
String JSON contendo o identificador do deviceCredential associado à API de Credenciais. Presente apenas para licenças do Astra Data Store. Os valores definidos são:

* Conforme o esquema de identificador Astra




| isEvaluation | string | Verdadeiro  a| 
String JSON que indica se a licença é uma licença de avaliação. Os valores definidos são:

* "true"
* "false"




| licenseProtocol | string | Verdadeiro  a| 
String JSON contendo o protocolo de licença extraído da licença. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| licenseText | string | Verdadeiro  a| 
String JSON contendo uma representação codificada em base64 do JSON da licença, conforme obtido do sistema de licenciamento NetApp. Esta string deve ser fornecida na ordem original de bytes para permitir a verificação da assinatura. Os valores definidos são:

* Está em conformidade com o esquema de dados codificados em base64




| validFromTimestamp | string | Verdadeiro  a| 
String JSON contendo um registro de data e hora indicando quando a licença se torna válida. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| validUntilTimestamp | string | Verdadeiro  a| 
String JSON contendo um registro de data e hora indicando quando a licença deixa de ser válida. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| produto | string | Verdadeiro  a| 
String JSON contendo a string do produto extraída da licença. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| productVersion | string | Verdadeiro  a| 
String JSON contendo a string de versão extraída da licença. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| produtoSN | string | Verdadeiro  a| 
String JSON contendo a string do número de série extraída da licença. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| características | string | Verdadeiro  a| 
String JSON contendo o valor do pacote extraído da licença. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| capacidade | string | Verdadeiro  a| 
String JSON contendo a capacidade extraída da licença.



| capacity2 | string | Verdadeiro  a| 
String JSON contendo a capacidade secundária extraída da licença.



| complementos | array[link:#addons["complementos"]] | Falso  a| 
Matriz JSON de objetos JSON contendo a lista de complementos da licença. Um complemento é uma alteração na licença que pode ocorrer em uma data futura.



| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| continuar | string | Falso  a| 



| contar | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====