---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-core-v1-upgrades-.html 
summary: Obtenha uma atualização 
---
= Obtenha uma atualização
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/upgrades/{upgrade_id}`#

Retorna o recurso da API Upgrade armazenado no corpo da resposta JSON.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| upgrade_id | string | caminho | Verdadeiro  a| 
ID da coleção de atualização a ser listada

|===


== Resposta

[source]
----
Status: 200, Returns the stored Upgrade API resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-upgrade"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| componentName | string | Verdadeiro  a| 
String JSON contendo o nome do tipo de software que pode ser atualizado. Os valores definidos são:

* "acc"
* "acs"
* "Trident"
* "kubernetes"




| componentInstance | string | Verdadeiro  a| 
String JSON contendo o URI do componente que pode ser atualizado. Os valores definidos são:

* Comprimento mínimo: 3
* Comprimento máximo: 4095




| ID do componente | string | Verdadeiro  a| 
String JSON contendo um identificador globalmente único do componente que pode ser atualizado. Os valores definidos são:

* Conforme o esquema de identificador Astra




| upgradeVersion | string | Verdadeiro  a| 
String JSON contendo o SemVer do arquivo de imagem do software para o qual pode ser feita a atualização. Os valores definidos são:

* Está em conformidade com o SemVer Schema




| currentVersion | string | Verdadeiro  a| 
String JSON contendo o SemVer atual da entidade a ser atualizada. Os valores definidos são:

* Está em conformidade com o SemVer Schema




| dependências | array[string] | Verdadeiro  a| 
Array JSON de strings JSON, cada uma contendo o UUID de uma atualização que deve ser concluída antes que esta atualização possa prosseguir. Usado para determinar quais atualizações serão realizadas como pré-requisitos e em qual ordem. Os valores definidos são:

* Conforme o esquema de identificador Astra




| estado | string | Verdadeiro  a| 
String JSON contendo um valor que indica o estado operacional da atualização. Se a atualização automática estiver habilitada, as atualizações serão iniciadas no estado "agendado". Caso contrário, as atualizações serão iniciadas no estado "proposto". Os valores definidos são:

* "Indisponível" - A atualização não está disponível no momento
* "Proposto" - A atualização foi proposta, mas não será executada automaticamente até ser aprovada
* "Agendado" - A atualização foi aprovada, mas ainda não está pronta para ser instalada devido a dependências, janelas de tempo ou recursos disponíveis
* "running" - A atualização está em andamento
* "Concluído" - A atualização foi concluída
* "Falha" - A atualização não foi concluída




| stateDesired | string | Verdadeiro  a| 
String JSON contendo um valor que indica o estado desejado para "state". Este campo só é incluído quando o usuário pode solicitar diretamente uma alteração no estado do recurso. Os valores definidos são:

* "Proposto" - A atualização não foi aprovada e não deve ser realizada
* "Agendado" - A atualização foi aprovada e deve ser realizada dentro do prazo especificado
* "Em execução" - A atualização deve ser realizada imediatamente, independentemente do período de tempo




| stateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Verdadeiro  a| 
Matriz JSON de objetos JSON que lista detalhes adicionais sobre o "estado" atual. Se não houver detalhes disponíveis, essa matriz estará vazia.

* Quantidade mínima de itens: 0




| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-upgrade",
  "version": "1.1",
  "id": "aa9a8e88-c012-55b1-b514-7cd94dc79008",
  "componentName": "trident",
  "componentInstance": "https://<dns_name>/accounts/0b311ae7-d89a-4a11-a52c-1349ca090415/topology/v1/clouds/fdda3ff3-a46a-43a4-902e-444fde2baeba/storageBackends/72d19c3c-eb43-4bec-b23e-a228c900aded",
  "componentID": "72d19c3c-eb43-4bec-b23e-a228c900aded",
  "upgradeVersion": "21.07.1",
  "currentVersion": "21.04.1",
  "dependencies": [],
  "state": "scheduled",
  "stateDesired": "scheduled",
  "stateDetails": [],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====