---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-k8s-v1-apps-schedules-.html 
summary: Consulte a programação 
---
= Consulte a programação
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/schedules/{schedule_id}`#

Retorna o recurso da API de Agendamento armazenado no corpo da resposta JSON.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| app_id | string | caminho | Verdadeiro  a| 
ID do recurso do aplicativo que o contém



| id_do_agendamento | string | caminho | Verdadeiro  a| 
ID da coleção de agendamentos a ser listada

|===


== Resposta

[source]
----
Status: 200, Returns the stored Schedule API resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-schedule"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| nome | string | Verdadeiro  a| 
String JSON contendo o nome da programação. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| habilitado | string | Verdadeiro  a| 
String JSON que indica se um agendamento está ativo. Os valores definidos são:

* "verdadeiro" - O cronograma está ativo
* "false" - O agendamento não está ativo Se não for especificado, o valor padrão é "true".




| granularidade | string | Verdadeiro  a| 
String JSON que indica a granularidade da programação. Os valores definidos são:

* "por hora"
* "diário"
* "semanalmente"
* "mensal"
* "personalizado"




| minuto | string | Verdadeiro  a| 
String JSON contendo um valor numérico que indica o minuto da hora (0 - 59) em que a programação deve ser executada. Os valores definidos são:

* A expressão regular definida é: "^[0-9]|[1-5][0-9]$" Este campo estará presente se granularidade estiver definida como "hourly", "daily", "weekly" ou "monthly". Ele será retornado com o valor "0" para agendamentos personalizados.




| hora | string | Falso  a| 
String JSON contendo um valor numérico que indica a hora do dia (0 - 23) em que a programação deve ser executada. Os valores definidos são:

* A expressão regular definida é: "^[0-9]|[1][0-9]|[2][0-3]$" Este campo está presente se granularidade estiver definida como "daily", "weekly" ou "monthly".




| dayOfWeek | string | Falso  a| 
String JSON contendo um valor numérico que indica o dia da semana (0-7) em que a programação deve ser executada. Os valores definidos são:

* A expressão regular definida é: "^[0-7]$" Este campo só está presente se granularidade estiver definida como "semanal".




| dayOfMonth | string | Falso  a| 
String JSON contendo um valor numérico que indica o dia do mês (1-31) em que a programação deve ser executada. Os valores definidos são:

* A expressão regular definida é: "^[1-9]|[1-2][0-9]|[3][0-1]$" Este campo só está presente se granularidade estiver definida como "monthly".




| recurrenceRule | string | Falso  a| 
String JSON contendo uma RFC-5545 Seção 3.8.5.3. Regra de recorrência. Para o parâmetro DTSTART, somente timestamps UTC (indicados pelo sufixo "Z") são suportados, e somente timestamps anteriores à hora atual são suportados. Para as partes da regra RECUR, "FREQ" e "INTERVAL" são as únicas partes suportadas. Para a parte da regra FREQ, "MINUTELY" e "HOURLY" são os únicos valores suportados. Este campo só está presente se granularidade estiver definida como "custom".



| snapshotRetention | string | Verdadeiro  a| 
String JSON contendo um valor numérico positivo que indica quantos snapshots devem ser mantidos. Zero indica que os snapshots devem ser excluídos após a criação de um backup. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63
* A expressão regular definida é: "^(0|([1-9][0-9]*))$"




| backupRetention | string | Verdadeiro  a| 
String JSON contendo um valor numérico positivo que indica quantos backups devem ser mantidos. Zero indica que nenhum backup deve ser criado. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63
* A expressão regular definida é: "^(0|([1-9][0-9]*))$"




| bucketID | string | Falso  a| 
String JSON contendo um ID de bucket opcional que indica onde o backup deve ser armazenado na criação. Se não for especificado, um bucket selecionado pelo sistema será usado. Os valores definidos são:

* Conforme o esquema de identificador Astra




| replicar | string | Falso  a| 
String JSON que indica se o agendamento aciona a replicação AppMirror para cada snapshot. Só entra em vigor se o aplicativo tiver um relacionamento AppMirror definido. Os valores definidos são:

* "verdadeiro" - O agendamento aciona a replicação do AppMirror
* "false" - O agendamento não aciona a replicação do AppMirror. Se não for especificado, o valor padrão é "false".




| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-schedule",
  "version": "1.3",
  "id": "49cbc480-5f7d-51e2-8f30-52b9a83a03b1",
  "name": "Backup Schedule",
  "enabled": "true",
  "granularity": "monthly",
  "minute": "0",
  "hour": "0",
  "dayOfMonth": "1",
  "snapshotRetention": "12",
  "backupRetention": "12",
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====