---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/get-accounts-topology-v1-clusters-clusternodes.html 
summary: Liste os nós do cluster para um cluster 
---
= Liste os nós do cluster para um cluster
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/clusters/{cluster_id}/clusterNodes`#

Retorna uma matriz JSON com todos os recursos correspondentes na coleção. Se campos individuais forem especificados na solicitação, a matriz JSON de itens conterá os campos solicitados para cada recurso correspondente na ordem especificada.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| cluster_id | string | caminho | Verdadeiro  a| 
ID do recurso de cluster que o contém



| incluir | string | consulta | Falso  a| 
Indica quais campos devem ser retornados ao listar uma coleção.

Exemplos de URL: "include=id", "include=id,name"

Exemplos OpenAPI: "id"

* exemplo: nome,instanceType




| limite | string | consulta | Falso  a| 
Indica o número máximo de recursos a serem retornados ao listar uma coleção.

Exemplos de URL: "limit=2"

Exemplos OpenAPI: "2"

|===


== Resposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| itens | array[Qualquer um de: link:#clusterNode_1_0_get_response_body["clusterNode_1.0_get_response_body"], array[]] | Verdadeiro  a| 



| metadados | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadeiro  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-clusterNodes",
  "version": "1.0",
  "items": [
    [
      "test-0",
      "e2-medium"
    ],
    [
      "test-1",
      "e2-medium"
    ],
    [
      "test-2",
      "e2-medium"
    ],
    [
      "test-3",
      "e2-micro"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidParams | array[link:#invalidParams["invalidParams"]] | Falso  a| 
Lista de parâmetros de consulta inválidos

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
etiquetas

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
String JSON contendo o nome do rótulo Definidos valores são:

* Comprimento mínimo: 1
* Comprimento máximo: 63
* A expressão regular definida é: "^([\S.]{1,253}\/)?([a-z0-9A-Z_.-]){1,63}$"




| valor | string | Verdadeiro  a| 
String JSON contendo o valor do rótulo Definidos valores são:

* Comprimento mínimo: 1
* Comprimento máximo: 63
* A expressão regular definida é: "^([a-z0-9A-Z_.-]){1,63}$"


|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_metadados_astra

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Conforme o esquema de metadados Astra


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Verdadeiro  a| 



| CriaçãoTimestamp | string | Verdadeiro  a| 



| Alteração do Timestamp | string | Verdadeiro  a| 



| CreatedBy | string | Verdadeiro  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
clusterNode_1.0_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "aplicação/astra-clusterNode"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| nome | string | Verdadeiro  a| 
String JSON contendo um valor que indica o nome do nó no Kubernetes. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| papel | string | Verdadeiro  a| 
String JSON contendo um valor que indica a função do Kubernetes para o nó. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| etiquetas | array[link:#labels["etiquetas"]] | Verdadeiro  a| 
Matriz JSON de objetos JSON, cada um contendo rótulos do Kubernetes associados ao nó. Se não houver detalhes disponíveis, essa matriz estará vazia.

* Itens mínimos: 0




| creationTime | string | Verdadeiro  a| 
String JSON contendo um timestamp ISO 8601 que indica quando o nó foi criado. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| IP externo | string | Verdadeiro  a| 
String JSON contendo um valor que indica o endereço IP interno do nó. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| IP interno | string | Verdadeiro  a| 
String JSON contendo um valor que indica o endereço IP externo do nó. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| zona | string | Verdadeiro  a| 
String JSON contendo um valor que indica a zona Kubernetes do nó. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| região | string | Verdadeiro  a| 
String JSON contendo um valor que indica a região do Kubernetes para o nó. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| instanceType | string | Verdadeiro  a| 
String JSON contendo um valor que indica o tipo de instância do Kubernetes para o nó. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| kernelVersion | string | Verdadeiro  a| 
String JSON contendo um valor que indica a versão do kernel usada pelo nó. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| osImage | string | Verdadeiro  a| 
String JSON contendo um valor que indica a imagem do sistema operacional usada pelo nó. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| numCpus | string | Verdadeiro  a| 
String JSON contendo um valor que indica o número de CPUs atribuídas ao nó. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| memória | string | Verdadeiro  a| 
String JSON contendo um valor que indica a quantidade de memória alocada ao nó. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| estado | string | Verdadeiro  a| 
String JSON contendo um valor que indica o estado operacional do nó. Os valores definidos são:

* "Em execução" - O nó está em execução normalmente
* "Provisionamento" - O nó está em processo de provisionamento
* "Descobrindo" - Aspectos do nó estão em processo de descoberta
* "Pendente" - O nó está agendado para descoberta
* "failed" - O nó está em estado de falha
* "Desconhecido" - O estado do nó não pode ser determinado




| metadados | link:#type_astra_metadata["tipo_metadados_astra"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Conforme o esquema de metadados Astra


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| continuar | string | Falso  a| 



| contar | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====