---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/get-accounts-k8s-v1-apps-appsnaps-appassets.html 
summary: Listar os recursos do aplicativo para um Snapshot do aplicativo 
---
= Listar os recursos do aplicativo para um Snapshot do aplicativo
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/appSnaps/{appSnap_id}/appAssets`#

Retorna uma matriz JSON com todos os recursos correspondentes na coleção. Se campos individuais forem especificados na solicitação, a matriz JSON de itens conterá os campos solicitados para cada recurso correspondente na ordem especificada.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| app_id | string | caminho | Verdadeiro  a| 
ID do recurso do aplicativo que o contém



| appSnap_id | string | caminho | Verdadeiro  a| 
ID do recurso appSnap que o contém



| incluir | string | consulta | Falso  a| 
Indica quais campos devem ser retornados ao listar uma coleção.

Exemplos de URL: "include=id", "include=id,name"

Exemplos OpenAPI: "id"

* exemplo: assetType,assetName




| limite | string | consulta | Falso  a| 
Indica o número máximo de recursos a serem retornados ao listar uma coleção.

Exemplos de URL: "limit=2"

Exemplos OpenAPI: "2"

|===


== Resposta

[source]
----
Status: 200, Returns a JSON array of all matching resources in the collection. If individual fields are specified in the request, the items JSON array will contain the fields requested for each matching resource in the order specified.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| itens | array[Qualquer um de: link:#appAsset_1_1_get_response_body["appAsset_1.1_get_response_body"], array[]] | Verdadeiro  a| 



| metadados | link:#type_astra_metadata_list["type_astra_metadata_list"] | Verdadeiro  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-appAssets",
  "version": "1.1",
  "items": [
    [
      "Pod",
      "mediawiki-69c6fcf864-2wx6l"
    ],
    [
      "ReplicaSet",
      "mediawiki-69c6fcf864"
    ],
    [
      "Service",
      "mediawiki"
    ],
    [
      "Deployment",
      "mediawiki"
    ]
  ],
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
GVK

Objeto JSON contendo um grupo/versão/tipo do Kubernetes.

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| grupo | string | Falso  a| 
String JSON contendo um identificador de grupo atribuído pelo Kubernetes. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| tipo | string | Falso  a| 
String JSON contendo um identificador de tipo atribuído pelo Kubernetes. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| versão | string | Falso  a| 
String JSON contendo um identificador de versão atribuído pelo Kubernetes. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254


|===
[role="api-collapsible-fifth-title"]
tipo_json

Objeto JSON contendo todo o conteúdo da definição do recurso Kubernetes.

[role="api-collapsible-fifth-title"]
etiquetas

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
String JSON contendo o nome do rótulo Definidos valores são:

* Comprimento mínimo: 1
* Comprimento máximo: 63
* A expressão regular definida é: "^([\S.]{1,253}\/)?([a-z0-9A-Z_.-]){1,63}$"




| valor | string | Verdadeiro  a| 
String JSON contendo o valor do rótulo Definidos valores são:

* Comprimento mínimo: 1
* Comprimento máximo: 63
* A expressão regular definida é: "^([a-z0-9A-Z_.-]){1,63}$"


|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_metadados_astra

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Conforme o esquema de metadados Astra


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Verdadeiro  a| 



| CriaçãoTimestamp | string | Verdadeiro  a| 



| Alteração do Timestamp | string | Verdadeiro  a| 



| CreatedBy | string | Verdadeiro  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
appAsset_1.1_get_response_body

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "aplicação/astra-appAsset"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| assetType | string | Verdadeiro  a| 
String JSON contendo um valor que indica o tipo de asset que está sendo descrito como obtido do Kubernetes. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| CriaçãoTimestamp | string | Verdadeiro  a| 
String JSON contendo um carimbo de data/hora indicando quando os metadados do Kubernetes foram criados. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| GVK | link:#GVK["GVK"] | Verdadeiro  a| 
Objeto JSON contendo um grupo/versão/tipo do Kubernetes.



| recurso | link:#type_json["tipo_json"] | Falso  a| 
Objeto JSON contendo todo o conteúdo da definição do recurso Kubernetes.



| ID do ativo | string | Verdadeiro  a| 
String JSON contendo um identificador atribuído pelo Kubernetes. Os valores definidos são:

* Conforme o esquema de identificador Astra




| etiquetas | array[link:#labels["etiquetas"]] | Verdadeiro  a| 
Matriz JSON de objetos JSON, cada um contendo um rótulo do Kubernetes associado ao recurso. Se não houver detalhes disponíveis, essa matriz estará vazia.

* Itens mínimos: 0




| assetName | string | Verdadeiro  a| 
String JSON contendo um nome atribuído pelo Kubernetes. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| namespace | string | Falso  a| 
String JSON contendo um namespace atribuído pelo Kubernetes. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 254




| metadados | link:#type_astra_metadata["tipo_metadados_astra"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Conforme o esquema de metadados Astra


|===
[role="api-collapsible-fifth-title"]
type_astra_metadata_list

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| continuar | string | Falso  a| 



| contar | número | Falso  a| 



| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====