---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/post-accounts-core-v1-subscriptions.html 
summary: Criar uma nova assinatura 
---
= Criar uma nova assinatura
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/subscriptions`#

Indica os valores desejados para o recurso da API de Subscription a ser criado.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}


|===


== Corpo da solicitação

Indica os valores desejados para o recurso da API de Subscription a ser criado.

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-subscription"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"
* "1,2"




| ID do perfil do cliente | string | Falso  a| 
String JSON contendo o ID do perfil do cliente de  http://authorize.net["Authorize.net"], que foi invocada pela interface do usuário, não está definida para o período de carência. Retorna uma string vazia durante a operação de leitura, caso não esteja definida. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63




| paymentFirstName | string | Falso  a| 
String JSON contendo um nome completo especificado pelo usuário, usado para faturamento de pagamentos. Especificado apenas quando a assinatura está sendo renovada. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| paymentLastName | string | Falso  a| 
String JSON contendo o sobrenome completo especificado pelo usuário, utilizado para faturamento da assinatura. Especificado apenas quando a assinatura está sendo renovada. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| paymentAddress | link:#paymentAddress["paymentAddress"] | Falso  a| 
Objeto JSON contendo uma coleção de strings JSON que especificam um endereço de cobrança. Especificado apenas quando a assinatura está sendo renovada. Se esta chave existir, todas as seis strings JSON contidas estarão presentes. Se nada for fornecido pelo usuário, a string estará vazia.



| ID do perfil de pagamento | string | Falso  a| 
String JSON contendo o ID do perfil de pagamento  http://Authorize.net["Authorize.net"] que foi invocado pela interface do usuário, não definido para o período de avaliação. Retorna uma string vazia durante a operação de leitura se não estiver definido. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63




| paymentExpiry | string | Falso  a| 
String JSON contendo um timestamp indicando quando o método de pagamento expira. Este valor é obtido do authorize.net(http://authorize.net[] e definido pela interface do usuário. Os valores definidos são:

* Em conformidade com o padrão de data e hora ISO-8601 Este campo não é retornado durante o período de avaliação.




| marketplace | string | Falso  a| 
String JSON que indica o marketplace para uma conta onde os pagamentos serão registrados. Valores definidos:

* "netapp"
* "azure"
* "aws"
* "gcp"




| termos | string | Verdadeiro  a| 
String JSON que indica o nível atual da conta. Os valores definidos são:

* "teste"
* "pago"




| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Falso  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
.Exemplo de solicitação
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-subscription",
  "version": "1.2",
  "terms": "trial"
}
----
====


== Resposta

[source]
----
Status: 201, Returns the newly created subscription resource in the JSON response body.
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-subscription"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"
* "1,2"




| id | string | Verdadeiro  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| ID do perfil do cliente | string | Verdadeiro  a| 
String JSON contendo o ID do perfil do cliente de  http://authorize.net["Authorize.net"], que foi invocada pela interface do usuário, não está definida para o período de carência. Retorna uma string vazia durante a operação de leitura, caso não esteja definida. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63




| ID do perfil de pagamento | string | Falso  a| 
String JSON contendo o ID do perfil de pagamento  http://Authorize.net["Authorize.net"] que foi invocado pela interface do usuário, não definido para o período de avaliação. Retorna uma string vazia durante a operação de leitura se não estiver definido. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63




| paymentExpiry | string | Falso  a| 
String JSON contendo um timestamp indicando quando o método de pagamento expira. Este valor é obtido do authorize.net(http://authorize.net[] e definido pela interface do usuário. Os valores definidos são:

* Em conformidade com o padrão de data e hora ISO-8601 Este campo não é retornado durante o período de avaliação.




| purchaseOrderNumber | string | Falso  a| 
String JSON contendo o número do pedido de compra para o método de pagamento. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 31




| marketplace | string | Falso  a| 
String JSON que indica o marketplace para uma conta onde os pagamentos serão registrados. Valores definidos:

* "netapp"
* "azure"
* "aws"
* "gcp"




| licenseSN | string | Falso  a| 
String JSON contendo o número de série da licença para o método de pagamento. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 31




| termos | string | Verdadeiro  a| 
String JSON que indica o nível atual da conta. Os valores definidos são:

* "teste"
* "pago"




| status | string | Verdadeiro  a| 
String JSON que indica o status atual da assinatura. Os valores definidos são:

* "ativo"
* "inativo"




| appLimit | número | Verdadeiro  a| 
Número JSON que indica o limite de aplicativos para esta assinatura. O valor -1 indica que não há limite.



| namespaceLimit | número | Verdadeiro  a| 
Número JSON que indica o limite de namespace para esta assinatura. O valor -1 indica que não há limite.



| subscriptionPeriod | número | Verdadeiro  a| 
Número JSON que indica o período de assinatura. O valor -1 indica que não há limite. Unidade: dias



| gracePeriod | número | Verdadeiro  a| 
Número JSON que indica o período de carência após o término da assinatura de avaliação ou o cancelamento de uma assinatura paga. Unidade: dias



| reminderBeforePeriod | número | Verdadeiro  a| 
Número JSON que indica a quantidade de dias antes do término da assinatura de avaliação, quando as notificações ao cliente serão iniciadas. O valor é expresso em dias, sendo -1 indicativo de que não se aplica.



| onboardStatus | string | Verdadeiro  a| 
String JSON que indica o status atual do processo de integração do cliente. Os valores válidos são "não iniciado", "em andamento", "sucesso", "falha". Os valores definidos são:

* "não iniciado"
* "em andamento"
* "sucesso"
* "falhou"




| costPerAppUnit | número | Verdadeiro  a| 
Número JSON que indica o custo por unidade do aplicativo. Para uma versão de avaliação, o valor é 0. Unidade: dólares americanos



| costPerNamespaceUnit | número | Verdadeiro  a| 
Número JSON que indica o custo por unidade de namespace. Para uma versão de avaliação, o valor é 0. Unidade: dólares americanos



| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Verdadeiro  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-subscription",
  "version": "1.2",
  "id": "40b4106f-b743-5d83-95c7-d539b2b45f63",
  "customerProfileID": "2157047189",
  "paymentProfileID": "E7CEB0A9F1BECA32A02493E1B31D5955",
  "paymentExpiry": "2022-02-01T00:00:00Z",
  "purchaseOrderNumber": "72384632",
  "marketplace": "netapp",
  "licenseSN": "278343",
  "terms": "trial",
  "status": "active",
  "appLimit": 0,
  "namespaceLimit": 10,
  "subscriptionPeriod": 90,
  "gracePeriod": 7,
  "reminderBeforePeriod": 30,
  "onboardStatus": "in progress",
  "costPerAppUnit": 0,
  "costPerNamespaceUnit": 0.005,
  "metadata": {
    "labels": [],
    "creationTimestamp": "2022-10-06T20:58:16.305662Z",
    "modificationTimestamp": "2022-10-06T20:58:16.305662Z",
    "createdBy": "8f84cf09-8036-51e4-b579-bd30cb07b269"
  }
}
----
====


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos inválidos no corpo da requisição

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos inválidos no corpo da requisição

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/2",
  "title": "Collection not found",
  "detail": "The collection specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
paymentAddress

Objeto JSON contendo uma coleção de strings JSON que especificam um endereço de cobrança. Especificado apenas quando a assinatura está sendo renovada. Se esta chave existir, todas as seis strings JSON contidas estarão presentes. Se nada for fornecido pelo usuário, a string estará vazia.

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| addressCountry | string | Verdadeiro  a| 
Cadeia JSON contendo o nome ou código do país associado ao endereço postal, conforme especificado na norma ISO 3166 Alpha-2. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 2




| addressLocality | string | Verdadeiro  a| 
String JSON contendo a localidade (por exemplo, cidade) associada ao endereço postal. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63




| addressRegion | string | Verdadeiro  a| 
String JSON contendo a região (por exemplo, estado) associada ao endereço postal. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63




| postalCode | string | Verdadeiro  a| 
String JSON contendo o código postal associado ao endereço postal. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63




| streetAddress1 | string | Verdadeiro  a| 
String JSON contendo o endereço da rua associado ao endereço postal. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63




| streetAddress2 | string | Falso  a| 
String JSON contendo informações opcionais de endereço de rua, caixa postal e outros dados adicionais. Os valores definidos são:

* Comprimento mínimo: 0
* Comprimento máximo: 63


|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do campo inválido no corpo da requisição



| razão | string | Verdadeiro  a| 
Motivo pelo qual o campo do corpo da solicitação é inválido

|===
====