---
sidebar: sidebar 
api: true 
explorer: true 
permalink: reference/put-accounts-core-v1-users-groups-.html 
summary: Modificar um grupo para um usuário 
---
= Modificar um grupo para um usuário
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/users/{user_id}/groups/{group_id}`#

Substitui todo o recurso armazenado pelo corpo da solicitação JSON fornecida, preservando os valores-chave que não podem ser modificados pelo usuário.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| ID do usuário | string | caminho | Verdadeiro  a| 
ID do recurso de usuário que o contém



| id_do_grupo | string | caminho | Verdadeiro  a| 
ID da coleção de grupos a ser listada

|===


== Corpo da solicitação

Substitui todo o recurso armazenado pelo corpo da solicitação JSON fornecida, preservando os valores-chave que não podem ser modificados pelo usuário.

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-group"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"




| id | string | Falso  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| nome | string | Falso  a| 
O nome do recurso do grupo. Se não for especificado na criação, o valor será definido como

* primeiro nome comum (CN) nomes distintos relativos (RDN) se encontrados no authID,
* authID, caso contrário. Se não for especificado na atualização, o valor será preservado sem modificação. Os valores definidos são:
* Comprimento mínimo: 1
* Comprimento máximo: 2048




| authProvider | string | Falso  a| 
O provedor de autenticação para o recurso de grupo. Os valores definidos são:

* "ldap"




| ID de autenticação | string | Falso  a| 
O Nome Distinto (DN) para um grupo LDAP. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 2048




| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Falso  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
.Exemplo de solicitação
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-group",
  "version": "1.1",
  "name": "my-qa-group",
  "authID": "CN=QA,CN=Groups,DC=example,DC=com"
}
----
====


== Resposta

[source]
----
Status: 204, Indicates if the group resource was updated.
----


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/7",
  "title": "Invalid JSON payload",
  "detail": "The request body is not valid JSON.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Resposta

[source]
----
Status: 500, Internal server error
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/34",
  "title": "Internal server error",
  "detail": "The server was unable to process this request.",
  "status": "500"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
====