---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-core-v1-licenses-.html 
summary: Modificar uma licença 
---
= Modificar uma licença
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/core/v1/licenses/{license_id}`#

Substitui todo o recurso armazenado pelo corpo da solicitação JSON fornecida, preservando os valores-chave que não podem ser modificados pelo usuário.

*Efeitos Colaterais*

* Os direitos de uso são recalculados para adicionar ou mesclar os direitos de licença visíveis por meio da Entitlement API.




== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| id_da_licença | string | caminho | Verdadeiro  a| 
ID da coleção de licenças a ser listada

|===


== Corpo da solicitação

Substitui todo o recurso armazenado pelo corpo da solicitação JSON fornecida, preservando os valores-chave que não podem ser modificados pelo usuário.

*Efeitos Colaterais*

* Os direitos de uso são recalculados para adicionar ou mesclar os direitos de licença visíveis por meio da Entitlement API.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "application/astra-license"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"




| id | string | Falso  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| alocação | string | Falso  a| 
String JSON contendo um ID que indica a que a licença está alocada. Presente somente quando a licença está alocada. Para licenças do Astra Control Center, este campo deve ser preenchido com o ID da conta e deve corresponder ao ID da conta especificado no URI POST. Os valores definidos são:

* Conforme o esquema de identificador Astra




| ID do host | string | Falso  a| 
String JSON contendo um identificador de host ao qual uma licença está vinculada. Presente apenas se a licença estiver vinculada a um host específico. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| ID de credenciais do dispositivo | string | Falso  a| 
String JSON contendo o identificador do deviceCredential associado à API de Credenciais. Presente apenas para licenças do Astra Data Store. Os valores definidos são:

* Conforme o esquema de identificador Astra




| isEvaluation | string | Falso  a| 
String JSON que indica se a licença é uma licença de avaliação. Os valores definidos são:

* "true"
* "false"




| licenseProtocol | string | Falso  a| 
String JSON contendo o protocolo de licença extraído da licença. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| licenseText | string | Falso  a| 
String JSON contendo uma representação codificada em base64 do JSON da licença, conforme obtido do sistema de licenciamento NetApp. Esta string deve ser fornecida na ordem original de bytes para permitir a verificação da assinatura. Os valores definidos são:

* Está em conformidade com o esquema de dados codificados em base64




| validFromTimestamp | string | Falso  a| 
String JSON contendo um registro de data e hora indicando quando a licença se torna válida. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| validUntilTimestamp | string | Falso  a| 
String JSON contendo um registro de data e hora indicando quando a licença deixa de ser válida. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| produto | string | Falso  a| 
String JSON contendo a string do produto extraída da licença. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| productVersion | string | Falso  a| 
String JSON contendo a string de versão extraída da licença. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| produtoSN | string | Falso  a| 
String JSON contendo a string do número de série extraída da licença. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| características | string | Falso  a| 
String JSON contendo o valor do pacote extraído da licença. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| capacidade | string | Falso  a| 
String JSON contendo a capacidade extraída da licença.



| capacity2 | string | Falso  a| 
String JSON contendo a capacidade secundária extraída da licença.



| complementos | array[link:#addons["complementos"]] | Falso  a| 
Matriz JSON de objetos JSON contendo a lista de complementos da licença. Um complemento é uma alteração na licença que pode ocorrer em uma data futura.



| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Falso  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
.Exemplo de solicitação
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-license",
  "version": "1.0",
  "allocation": "4185d09b-6687-4801-a832-c005a9d94f41",
  "licenseText": "ewogICAic3RhdHVzUmVzcCI6ewogMTYwNzAwIgp9"
}
----
====


== Resposta

[source]
----
Status: 204, Indicates if the license resource was updated.
----


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos inválidos no corpo da requisição

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
complementos

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| startDate | string | Falso  a| 
String JSON contendo um carimbo de data/hora indicando quando este complemento se torna válido. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| endDate | string | Falso  a| 
String JSON contendo um carimbo de data/hora indicando quando este complemento deixa de ser válido. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| características | string | Falso  a| 
String JSON contendo a lista de funcionalidades associadas a este complemento. Os valores definidos são:

* O conteúdo da string não foi validado pelo esquema.




| capacidade | string | Falso  a| 
String JSON contendo a capacidade extraída do complemento. Os valores definidos são:

* Conteúdo da string não validado pelo esquema




| licenseProtocol | string | Falso  a| 
String JSON contendo o protocolo de licença associado a este complemento. Os valores definidos são:

* Conteúdo da string não validado pelo esquema


|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do campo inválido no corpo da requisição



| razão | string | Verdadeiro  a| 
Motivo pelo qual o campo do corpo da solicitação é inválido

|===
====