---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-topology-v1-managedclusters-.html 
summary: Modificar um cluster gerenciado 
---
= Modificar um cluster gerenciado
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/topology/v1/managedClusters/{managedCluster_id}`#

Substitui todo o recurso armazenado pelo corpo da solicitação JSON fornecida, preservando os valores-chave que não podem ser modificados pelo usuário.

*Efeitos Colaterais*

* Quando defaultStorageClass for alterado, a classe de armazenamento padrão do Kubernetes será atualizada.




== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| managedCluster_id | string | caminho | Verdadeiro  a| 
ID da coleção managedCluster a ser listada

|===


== Corpo da solicitação

Substitui todo o recurso armazenado pelo corpo da solicitação JSON fornecida, preservando os valores-chave que não podem ser modificados pelo usuário.

*Efeitos Colaterais*

* Quando defaultStorageClass for alterado, a classe de armazenamento padrão do Kubernetes será atualizada.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "aplicação/astra-managedCluster"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"
* "1,1"
* "1,2"
* "1,3"




| id | string | Falso  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| nome | string | Falso  a| 
String JSON contendo um nome para o cluster. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63
* Essa string é validada internamente para evitar ataques de XSS, Unicode, travessia de diretório e injeção de SQL.




| estado | string | Falso  a| 
Cadeia JSON contendo um valor que indica o estado operacional do cluster. Os valores definidos são:

* "Pendente" - O cluster está agendado para descoberta
* "descobrindo" - O cluster está em processo de descoberta
* "Provisionamento" - O cluster está em processo de provisionamento
* "Em execução" - O cluster está em execução normalmente
* "failed" - O cluster está em estado de falha permanente
* "removido" - O cluster não está acessível no momento
* "Desconhecido" - O estado do cluster não pode ser determinado




| restoreTargetSupported | string | Falso  a| 
String JSON contendo um valor que indica a capacidade do cluster gerenciado de ser um _alvo_ de operações de gerenciamento de dados de aplicativos. Os valores definidos são:

* "verdadeiro" - O cluster é um alvo elegível para operações de gerenciamento de dados de aplicativos.
* "falso" - O cluster _não_ é um alvo elegível para operações de gerenciamento de dados de app.




| snapshotSupported | string | Falso  a| 
String JSON contendo um valor que indica a capacidade do cluster gerenciado de executar operações semelhantes a backup de gerenciamento de dados de aplicativos. Os valores definidos são:

* "verdadeiro" - O cluster está apto a executar operações de gerenciamento de dados de aplicativos.
* "false" - O cluster _não_ está qualificado para executar operações de gerenciamento de dados do aplicativo.




| stateUnready | array[string] | Falso  a| 
Matriz JSON de strings JSON, cada uma indicando um motivo pelo qual o cluster não consegue transitar para o estado "em execução", quando há problemas enquanto está no estado "em execução" ou por que transitou para o estado "com falha" ou "removido". Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 127




| managedState | string | Falso  a| 
String JSON contendo um valor que indica o estado de gerenciamento do cluster. Os valores definidos são:

* "Pendente" - O cluster está agendado para ser descoberto ou adicionado
* "inelegível" - O cluster está em estado "em execução", não está sob gerenciamento e não é elegível para gerenciamento. O motivo ou motivos dessa inelegibilidade são fornecidos no valor da chave unready
* "Não gerenciado" - O cluster está em um estado "em execução" ou "com falha", não está sob gerenciamento e é elegível para gerenciamento
* "Gerenciando" - O cluster está em estado "em execução" e está em processo de gerenciamento
* "Gerenciado" - O cluster está em um estado "em execução", "com falha" ou "removido" e está sob gerenciamento




| protectionState | string | Falso  a| 
String JSON contendo um valor que indica o estado de proteção do cluster. Os valores definidos são:

* "full" - A classe de armazenamento padrão do cluster suporta snapshots
* "Parcial" - O cluster possui apenas classes de armazenamento que não suportam snapshots
* "atRisk" - A classe de armazenamento padrão do cluster não suporta snapshots




| protectionStateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falso  a| 
Matriz JSON de objetos JSON que lista detalhes adicionais sobre o estado de proteção atual, incluindo o motivo pelo qual esse estado foi atingido. Se não houver detalhes disponíveis, essa matriz estará vazia. Os valores definidos são:

* Quantidade mínima de itens: 0




| managedStateUnready | array[string] | Falso  a| 
Matriz JSON de strings JSON, cada uma indicando um motivo pelo qual o cluster não é elegível para ser gerenciado. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 127




| managedTimestamp | string | Falso  a| 
String JSON contendo o carimbo de data/hora que indica quando o cluster foi colocado sob gerenciamento. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601. Esta chave só é retornada quando um cluster tem um managedState de "managed".




| tridentVersion | string | Falso  a| 
String JSON contendo a versão do Trident instalada no cluster. Os valores definidos são:

* Em conformidade com o esquema de versão do software




| acpVersion | string | Falso  a| 
String JSON contendo a versão do Astra Control Provisioner instalada no cluster. Os valores definidos são:

* Em conformidade com o esquema de versão do software




| tridentManagedState | string | Falso  a| 
String JSON contendo um de um conjunto de valores enumerados que indicam o estado de gerenciamento do Trident neste cluster. Os valores definidos são:

* "Gerenciado" - a instância Trident no cluster é gerenciada pelo Astra
* "Não gerenciado" - a instância Trident no cluster não é gerenciada pelo Astra




| tridentManagedStateDesired | string | Falso  a| 
String JSON contendo um valor que indica o estado de gerenciamento desejado para Trident. Os valores definidos são:

* "managed" - Gerencie Trident neste cluster
* "Não gerenciado" - Não gerencie Trident neste cluster




| tridentManagedStateDetails | array[link:#type_astra_stateDetail["type_astra_stateDetail"]] | Falso  a| 
Matriz JSON de objetos JSON que lista detalhes adicionais sobre o motivo da transição do "state" para "managed" ou "unmanaged". + Se não houver detalhes disponíveis, esta matriz estará vazia.

* Quantidade mínima de itens: 0




| tridentManagedStateAllowed | array[string] | Falso  a| 
Estados que podem ser solicitados em um determinado tridentManagedState. Os seguintes estados podem ser solicitados em cada estado definido:

* "gerenciado": "gerenciado"
* "não gerenciado": "não gerenciado"




| inUse | string | Falso  a| 
String JSON contendo um valor que indica se o cluster possui algum aplicativo gerenciado e, portanto, não pode ser excluído. Os valores definidos são:

* "falso" - O cluster não é gerenciado ou é gerenciado, mas não possui aplicativos gerenciados associados a ele
* "verdadeiro" - O cluster é gerenciado e possui aplicativos gerenciados associados a ele




| accHost | string | Falso  a| 
String JSON que indica que este cluster hospeda a instância do Astra Control Center que está sendo acessada no momento. Os valores definidos são:

* "true" - Este cluster está hospedando a instância do Astra Control Center que está sendo acessada no momento.




| clusterType | string | Falso  a| 
String JSON contendo um valor que indica o tipo de cluster. Os valores definidos são:

* "gke" - Kubernetes hospedado no Google Kubernetes Engine
* "aks" - Kubernetes hospedado no serviço de Kubernetes do Microsoft Azure
* "eks" - Kubernetes hospedado no Amazon Elastic Kubernetes Service
* "rke" - O cluster é do tipo Rancher
* "tanzu" - O cluster é do tipo Tanzu Kubernetes Grid
* "openshift" - O cluster é do tipo OpenShift
* "anthos" - O cluster é do tipo GKE Anthos
* "kubernetes" - O cluster é Kubernetes genérico




| clusterVersion | string | Falso  a| 
String JSON contendo a representação semântica de versionamento do ambiente do cluster. Para clusters Kubernetes, esta é a versão do Kubernetes. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 31




| clusterVersionString | string | Falso  a| 
String JSON contendo um valor que indica as informações de versionamento estendidas para o ambiente de cluster. Para clusters Kubernetes, esta é a versão completa do Kubernetes. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 31




| clusterCreationTimestamp | string | Falso  a| 
String JSON contendo o carimbo de data/hora que indica quando o cluster foi criado originalmente. Os valores definidos são:

* Em conformidade com o esquema de data e hora ISO-8601




| espaços de nomes | array[string] | Falso  a| 
Matriz JSON de strings JSON, cada uma indicando um namespace dentro do cluster. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 253




| defaultStorageClass | string | Falso  a| 
String JSON contendo um ID de classe de armazenamento que corresponde à classe de armazenamento padrão, conforme definida no Kubernetes. Os valores definidos são:

* Está em conformidade com o esquema de identificação Astra. Se não estiver incluído, significa que ainda não foi descoberto.




| cloudID | string | Falso  a| 
String JSON contendo um valor que indica o ID da nuvem na qual o cluster está sendo executado. Os valores definidos são:

* Conforme o esquema de identificador Astra




| ID da credencial | string | Falso  a| 
String JSON contendo um valor que indica o ID da credencial que contém o arquivo kubeconfig do cluster. Os valores definidos são:

* Conforme o esquema de identificador Astra




| localização | string | Falso  a| 
String JSON contendo um valor fornecido pela nuvem na qual o cluster está sendo executado, indicando a localização específica do cluster nessa nuvem. Os valores definidos são:

* Comprimento mínimo: 1
* Comprimento máximo: 63




| isMultizonal | string | Falso  a| 
String JSON contendo um valor fornecido pela nuvem na qual o cluster está sendo executado, indicando se o cluster abrange duas ou mais zonas de disponibilidade. Os valores definidos são:

* "verdadeiro" - O cluster abrange duas ou mais zonas de disponibilidade
* "falso" - O cluster está totalmente localizado dentro de uma única zona de disponibilidade




| ID da rota privada | string | Falso  a| 
String JSON contendo o locationID para clusters privados.

* Comprimento mínimo: 1
* Comprimento máximo: 255




| ID do serviço de API | string | Falso  a| 
String JSON contendo o UUID do objeto de serviço da api do Kubernetes (k8s). Usada para identificar um cluster de forma única.



| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Falso  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
.Exemplo de solicitação
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-managedCluster",
  "version": "1.3",
  "defaultStorageClass": "0b146cda-7fc1-4f32-804c-8130a38a7e1c"
}
----
====


== Resposta

[source]
----
Status: 204, Indicates if the managedCluster resource was updated.
----


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos inválidos no corpo da requisição

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos inválidos no corpo da requisição

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
additionalDetails

[role="api-collapsible-fifth-title"]
type_astra_stateDetail

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| additionalDetails | link:#additionalDetails["additionalDetails"] | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do campo inválido no corpo da requisição



| razão | string | Verdadeiro  a| 
Motivo pelo qual o campo do corpo da solicitação é inválido

|===
====