---
sidebar: sidebar 
api: true 
explorer: false 
permalink: reference/put-accounts-k8s-v1-apps-executionhookoverrides-.html 
summary: Modificar um recurso de substituição de gancho de execução 
---
= Modificar um recurso de substituição de gancho de execução
:allow-uri-read: 


[.api-doc-operation .api-doc-operation-put]#PUT# [.api-doc-code-block]#`/accounts/{account_id}/k8s/v1/apps/{app_id}/executionHookOverrides/{executionHookOverride_id}`#

Substitui todo o recurso armazenado pelo corpo da solicitação JSON fornecida, preservando os valores-chave que não podem ser modificados pelo usuário.

*Efeitos Colaterais*

* Qualquer gancho de execução com um valor hookType de "netapp" que se aplique ao aplicativo especificado será desativado se o valor de "enabled" for alterado de "true" para "false" durante a operação de substituição.
* Qualquer gancho de execução com um valor hookType de "netapp" que se aplique ao aplicativo especificado será ativado se o valor de "enabled" for alterado de "false" para "true" durante a operação de substituição.



CAUTION: Esta operação está obsoleta.



== Parâmetros

[cols="5*"]
|===
| Nome | Tipo | Em | Obrigatório | Descrição 


| id_da_conta | string | caminho | Verdadeiro  a| 
ID do recurso de conta que o contém

* exemplo: {{.Account}}




| app_id | string | caminho | Verdadeiro  a| 
ID do recurso do aplicativo que o contém



| executionHookOverride_id | string | caminho | Verdadeiro  a| 
ID da coleção executionHookOverride a ser listada

|===


== Corpo da solicitação

Substitui todo o recurso armazenado pelo corpo da solicitação JSON fornecida, preservando os valores-chave que não podem ser modificados pelo usuário.

*Efeitos Colaterais*

* Qualquer gancho de execução com um valor hookType de "netapp" que se aplique ao aplicativo especificado será desativado se o valor de "enabled" for alterado de "true" para "false" durante a operação de substituição.
* Qualquer gancho de execução com um valor hookType de "netapp" que se aplique ao aplicativo especificado será ativado se o valor de "enabled" for alterado de "false" para "true" durante a operação de substituição.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 
Tipo de mídia do recurso. Os valores definidos são:

* "aplicação/astra-executionHookOverride"




| versão | string | Verdadeiro  a| 
Versão do recurso. Os valores definidos são:

* "1,0"




| id | string | Falso  a| 
Identificador globalmente único do recurso. Os valores definidos são:

* Em conformidade com o esquema UUIDv4




| ID do gancho de execução | string | Falso  a| 
String JSON contendo o ID de um gancho de execução. Os valores definidos são:

* Está em conformidade com o esquema de identificadores Astra. Permite apenas o executionHookID de um recurso de gancho de execução com um valor hookType de "netapp".




| habilitado | string | Falso  a| 
String JSON que indica se o gancho de execução está habilitado para o aplicativo especificado. Os valores definidos são:

* "true" - O gancho de execução está habilitado e será executado em uma ordem especificada
* "falso" - O gancho de execução está desativado e não pode ser executado




| ID do aplicativo | string | Falso  a| 
String JSON contendo o ID associado ao aplicativo ao qual a substituição está vinculada. Os valores definidos são:

* Conforme o esquema de identificador Astra




| metadados | link:#type_astra_metadata_update["type_astra_metadados_update"] | Falso  a| 
Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


|===
.Exemplo de solicitação
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "application/astra-executionHookOverride",
  "version": "1.0",
  "enabled": "false"
}
----
====


== Resposta

[source]
----
Status: 204, Indicates if the executionHookOverride resource was updated.
----


== Resposta

[source]
----
Status: 401, Unauthorized
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/3",
  "title": "Missing bearer token",
  "detail": "The request is missing the required bearer token.",
  "status": "401"
}
----
====


== Resposta

[source]
----
Status: 400, Bad request
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos inválidos no corpo da requisição

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/5",
  "title": "Invalid query parameters",
  "detail": "The supplied query parameters are invalid.",
  "status": "400"
}
----
====


== Resposta

[source]
----
Status: 409, Conflict
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 



| invalidFields | array[link:#invalidFields["invalidFields"]] | Falso  a| 
Lista de campos inválidos no corpo da requisição

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/10",
  "title": "JSON resource conflict",
  "detail": "The request body JSON contains a field that conflicts with an idempotent value.",
  "status": "409"
}
----
====


== Resposta

[source]
----
Status: 403, Forbidden
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/11",
  "title": "Operation not permitted",
  "detail": "The requested operation isn't permitted.",
  "status": "403"
}
----
====


== Erro

[source]
----
Status: 404, Not found
----
[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| tipo | string | Verdadeiro  a| 



| título | string | Verdadeiro  a| 



| detalhe | string | Verdadeiro  a| 



| status | string | Verdadeiro  a| 



| ID de correlação | string | Falso  a| 

|===
.Exemplo de resposta de erro
[%collapsible]
====
[source, json, subs="+macros"]
----
{
  "type": "https://astra.netapp.io/problems/1",
  "title": "Resource not found",
  "detail": "The resource specified in the request URI wasn't found.",
  "status": "404"
}
----
====


== Definições

.Ver definições
[%collapsible]
====
[role="api-collapsible-fifth-title"]
tipo_astra_label

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 



| valor | string | Verdadeiro  a| 

|===
[role="api-collapsible-fifth-title"]
type_astra_metadados_update

Metadados especificados pelo cliente e pelo serviço associados ao recurso. Os valores definidos são:

* Está em conformidade com o esquema de metadados Astra. Se não for especificado na criação, um objeto de metadados será criado sem rótulos. Se não for especificado na atualização, os rótulos do objeto de metadados, creationTimestamp e createdBy, serão preservados sem modificação.


[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| etiquetas | array[link:#type_astra_label["tipo_astra_label"]] | Falso  a| 



| CriaçãoTimestamp | string | Falso  a| 



| Alteração do Timestamp | string | Falso  a| 



| CreatedBy | string | Falso  a| 



| modifiedBy | string | Falso  a| 

|===
[role="api-collapsible-fifth-title"]
invalidParams

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do parâmetro de consulta inválido



| razão | string | Verdadeiro  a| 
Motivo pelo qual o parâmetro de consulta é inválido

|===
[role="api-collapsible-fifth-title"]
invalidFields

[cols="4*"]
|===
| Nome | Tipo | Obrigatório | Descrição 


| nome | string | Verdadeiro  a| 
Nome do campo inválido no corpo da requisição



| razão | string | Verdadeiro  a| 
Motivo pelo qual o campo do corpo da solicitação é inválido

|===
====