---
sidebar: sidebar 
permalink: workflows/wf_delete_backup.html 
keywords:  
summary: Pode eliminar uma cópia de segurança associada a uma aplicação. 
---
= Eliminar uma cópia de segurança
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pode eliminar uma cópia de segurança associada a uma aplicação.



=== Antes de começar

Você deve ter o seguinte:

* ID do aplicativo que possui o backup. Se necessário, você pode usar o fluxo de trabalho link:wf_list_man_apps.html["Liste as aplicações"] para localizar o aplicativo.
* ID da cópia de segurança que pretende eliminar. Se necessário, você pode usar o fluxo de trabalho link:wf_list_backups.html["Liste os backups"] para localizar o instantâneo.




=== 1. Eliminar a cópia de segurança

Execute a seguinte chamada de API REST.


NOTE: Você pode forçar a exclusão de um backup com falha usando o cabeçalho de solicitação opcional, conforme descrito abaixo.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| ELIMINAR | /Accounts/ k8s/v1/apps//app_id/appBackups/ appBackup_id 
|===


===== Parâmetros de entrada adicionais

Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| id da aplicação | Caminho | Sim | Identifica o aplicativo gerenciado que possui o backup. 


| id de cópia de segurança | Caminho | Sim | Identifica o backup a ser excluído. 


| forçar a eliminação | Colhedor | Não | Usado para forçar a exclusão de um backup com falha. 
|===


===== Curl exemplo: Exclua um único backup para o aplicativo

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appBackups/<BACKUP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Curl exemplo: Exclua um único backup para o aplicativo com a opção forçar

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appBackups/<BACKUP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --header 'Force-Delete: true'
----